

<?php

$name = $this->appConfig['system']['namesite'];

$site = $this->appConfig['system']['linksite'];

?>
<script   src="https://pilot.paylink.sa/assets/js/paylink.js"></script>



<div class="footer-menu"><ul class="menu menu2">
<li><a href="index.php" target="_blank" title="الصفحة الرئيسية">الصفحة الرئيسية</a></li>
<li><a href="manual.php" target="_blank" title="دليل اللعبة">دليل اللعبة</a></li>
<li><a href="login.php?terms" target="_blank" title="قوانين اللعبه">قوانين اللعبة</a></li>
<div style="text-align:center"><span style="font-size:small"><span style="color:#e74c3c">جميع الحقوق محفوظة &copy; عودة التتار <?php echo date('Y'); ?></span></span></div>

<div style="text-align: center;"><br /></div>
<?
/*
<li><a href="manual.php" target="_blank" title="تعليمات">تعليمات</a></li>
<li><a href="training.php" target="_blank" title="دوره تدريبيه">دوره تدريبيه</a></li>
*/
?>
</ul></div>
<?
echo '<div id="mfoot"><div class="copyright">';
echo '<a href=""> <span style="font-family:comic sans ms,cursive;"><img src=""></span></a>';
echo '</div></div>';
?>
