

<?php

$name = $this->appConfig['system']['namesite'];

$site = $this->appConfig['system']['linksite'];

?>
<script   src="https://pilot.paylink.sa/assets/js/paylink.js"></script>



<div class="footer-menu"><ul class="menu menu2">
<li><a href="index.php" target="_blank" title="الصفحة الرئيسية">الصفحة الرئيسية</a></li>
<li><a href="manual.php" target="_blank" title="دليل اللعبة">دليل اللعبة</a></li>
<li><a href="login.php?terms" target="_blank" title="قوانين اللعبه">قوانين اللعبة</a></li>
<div style="text-align:center"><strong><span style="color:#e74c3c"><span style="font-size:small">&nbsp;</span>&nbsp;</span></strong><span style="font-size:small"><span style="color:#e74c3c">جميع الحقوق محفوظه </span><a href="https://www.smartservs.com/"><span style="color:#e74c3c">سمارت سيرفس</span></a><span style="color:#e74c3c"> | </span><a href="https://www.smartservs.com/tatarwar/"><span style="color:#e74c3c">عودة التتار</span></a></span><strong><span style="font-size:small"><span style="color:#e74c3c">&copy;</span></span></strong></div>

<div style="text-align: center;"><br /></div>
<?
/*
<li><a href="manual.php" target="_blank" title="تعليمات">تعليمات</a></li>
<li><a href="training.php" target="_blank" title="دوره تدريبيه">دوره تدريبيه</a></li>
*/
?>
</ul></div>
<?
echo '<div id="mfoot"><div class="copyright">';
echo '<a href=""> <span style="font-family:comic sans ms,cursive;"><img src=""></span></a>';
echo '</div></div>';
?>
