<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
        <title><?php echo $this->title;?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="imagetoolbar" content="no" />
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <link href="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>default/lang/<?php echo $this->appConfig['system']['lang'];?><?php echo '/lang.css'.$this->getAssetVersion();?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>default/lang/<?php echo $this->appConfig['system']['lang'];?><?php echo '/compact.css'.$this->getAssetVersion();?>" rel="stylesheet" type="text/css" />
        <script src="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>/js/core.js<?php echo $this->getAssetVersion();?>" type="text/javascript"></script>
<?php 
if (($this->contentCssClass ?? '') == 'payment') {
?>
<style type="text/css">html,body{margin:0em;padding:0em;background-color:#e9e9e9;font-size:11px;font-family:Verdana,Arial,Helvetica,sans-serif;color:#333;direction:rtl}div.messagebox{position:relative;margin:75px auto 75px auto;padding:20px;width:300px;background-color:#fff;border:2px solid #d6d6d6;text-align:center;font-size:15px;font-weight:bold;white-space:nowrap}</style></head>
<?php
}
?>
<body class="manual">
        <?php 
$this->printContent();
?>
</body>
<script type="text/javascript">init();</script>
</html>