uploads = []
outputs = []

[[generated]]
id = "O058D0HC5ElXFQ0Bsaitq"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "eWKmfe4uJqp8u-1UOTNia"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "generated_image"
