<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php
if ( $this->data['blocked_time'] > time() ){
$time =  $this->data['blocked_time'];
$name =  $this->data['name'];
$timeout =  date('Y/m/d H:i:s',$time);
?>
<h1 class="titleInHeader">لاعب موقوف ( <font color="red"><?php echo $name; ?></font> )</h1>
<div style="padding-top:50px;">
<p style="text-align:center;font-weight:bold;font-size: 16px;">لقد تم حظرك بسبب انتهاكك <a href='login?terms'>لقوانين اللعبه</a>.</p><br>
<p style="text-align:center;font-weight:bold;font-size: 16px;">سبب الحظر: <span class="error"><?php echo $this->data['blocked_reason']; ?></span></p><br>
<p style="text-align:center;font-weight:bold;font-size: 16px;">لمناقشة امر الحظر يرجى مراسلة <a href="profile?uid=1">الدعم الفني</a></p><br>
<div style="text-align:center;font-weight:bold;font-size: 16px;">بقي على رفع الحظر : <?php 
if ( ($timeout > date('Y/m/d H:i:s'))){
echo "<font color='black'><font style='font-size: 22px; color: orange; font-weight: bold; text-shadow: 1px 1px #000;'><span id='timer1'>". TimeAgo(strtotime($timeout) - time()) ."</span></font>";
}
?></div>
</div>
<?php 
}
?>
</body>
</html>