<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php
/**
* @   PROJECT WAS MADE FOR SMART SERVS
* @   WHATS APP : 00966501494220 
* @   VISIT : WWW.REDSEA-H.COM
* @   ALL COPY RIGHTS RESERVED PROGRAMMED BY RED SEA HOST 
* @   THIS PROJECT WAS MADE BY THE REGISTERED RED SEA HOST UNDER THE NAME OF WWW.REDSEA-H.COM
**/
echo "<h1>";
echo "الدردشة";
echo "</h1>\r\n";
echo '<s';
echo 'tyle type="text/css">
#chatbox {
	text-align:left;
	margin:0 auto;
	margin-bottom:25px;
	padding:10px;
	background:#fff;
	height:270px;
	width:430px;
	border:1px solid #71D000;
	overflow:auto;
}
#usermsg {
	width:395px;
	border:1px solid #71D000;
}
#submit { width: 60px; }
.msgln { margin:0 0 2px 0;direction:ltr }

#chatbox {
    background: #def5ff40;
    width: 95%;
    height: calc(60vh - 100px) !important;
    min-height: 300px;
    border: 1px solid blue;
    text-align: right;
    overflow-x: visible;
    overflow-y: auto;
    border: 2px solid silver;
    border-right: 1px solid silver;
    border-left: 1px solid silver;
}


.y0 .x1 {
    border-radius: 0 6px 6px 0;
    padding: 2px 5px;
    width: 100px;
    max-width: 100px;
    text-align: center;
    display: inline-block;
    /*height: 100%;*/
    vertical-align: middle;
    font-size: 15px;
    font-weight: 900 !important;
}



#usermsg {
    margin: 4px 0 0 0;
    padding: 5px;
    font-size: 16px;
    height: 40px;
    min-height: 40px;
    width: 98%;
    border: 2px solid silver;
    border-right: 1px solid silver;
    border-left: 1px solid silver;
    text-align: right;
}
input:not([type]):hover, input[type=email]:hover, input[type=text]:hover, input[type=password]:hover {
    box-shadow: 0 0 5px #fbba01;
}
option, input[type=radio], input[type=checkbox], input[type=tel], input[type=email], input[type=password], input[type=text] {
    height: 20px!important;
    font-size: 17px;
}

#submitmsg {
    width: 220px;
    height: 30px;
    border-top: none;
    border-radius: 0 0 5px 5px;
    border: 1px solid silver;
    text-align: center;
    line-height: 30px;
    color: black;
    background: #e6e1e8;
    font-weight: 900;
    font-family: Helvetica,Arial,Verdana,sans-serif;
}

.y0 .x1 {
    background-color: #e6e6e6;
    word-break: break-all;
}
.y0 .x1 {
    border-radius: 0 6px 6px 0;
    padding: 2px 5px;
    width: 104px;
    max-width: 104px;
    text-align: center;
    display: inline-block;
    /*height: 100%;*/
    vertical-align: middle;
    font-size: 15px;
    font-weight: 900 !important;
}


.y0 .x0 {
	float: left;
    border-radius: 10px 0 0 10px;
    padding: 2px 8px;
    width: 375px;
    max-width: 375px;
    text-align: right;
    display: inline-block;
    */height: 100%;*/
    background: #f2f2f2;
    vertical-align: middle;
    word-wrap: break-word;
    border-right: 0;
    font-size: 15px;
    font-weight: 900 !important;
}
.ScrollBar_v1::-webkit-scrollbar {
    width: 15px;
}

.ScrollBar_v1::-webkit-scrollbar-thumb {
    background: #888;
}

.ScrollBar_v1::-webkit-scrollbar-track {
    background: #f1f1f1;
}
</style>
';
echo '<s';
echo 'cript type="text/javascript" src="core-f/style-f/js/jquery.min.js';
echo $this->getAssetVersion(  );
echo '"></script>
';
echo '<s';
echo 'cript type="text/javascript">
// jQuery Document
$(document).ready(function(){
	$("#chatbox").scrollTop($("#chatbox")[0].scrollHeight);
	//If user submits the form
	function SendMsg(){
		var clientmsg = $("#usermsg").val();
		if(clientmsg != \'\'){
			$.post("chat.php", {text: clientmsg});
			$("#usermsg").attr("value", "");
		}
		$("#usermsg").focus();
	}
	$("#submitmsg").click(function(){
		SendMsg();
		return false;
	});
	//Load th';
echo 'e file containing the chat log
	function loadLog(){
		var oldscrollHeight = $("#chatbox").attr("scrollHeight") - 20;
		$.ajax({
			url: "ajaxchat.php",
			cache: false,
			success: function(html){
				$("#chatbox").html( html); //Insert chat log into the #chatbox div
				var newscrollHeight = $("#chatbox").attr("scrollHeight") - 20;
				if(newscrollHeight > oldscrollHeight){
					$(';
echo '"#chatbox").animate({ scrollTop: newscrollHeight }, \'normal\'); //Autoscroll to bottom of div
				}
		  	},
		});
	}
	setInterval (loadLog, 2500);	//Reload file every 2.5 seconds
	$(\'#usermsg\').bind(\'keypress\', function(e) {
		//alert(e.keyCode);
		var code = (e.keyCode ? e.keyCode : e.which);
		 if(code == 13) { //Enter keycode
		   	SendMsg();
			return false;
		 }
	});
});
</sc';
echo 'ript>
<div id="chatbox" class="ScrollBar_v1">
';
$storCtat = array( );

                        $colors = ["#84674e",'#0b91b2','#6ebe22','#a93eab','#3559b0']; 
while ( $this->chats->next( ) )
{
    $redseahost = $this->Filter->FilterWords( $this->chats->row['text'] );
    $storCtat[$this->chats->row['ID']] = array(
        date( "H:i", $this->chats->row['date'] ),
        $this->chats->row['username'],
        $redseahost,
        $this->chats->row['userid']
    );

                        $storCtat[$this->chats->row['ID']] = array(date( "H:i", $this->chats->row['date'] ),$this->chats->row['username'],$redseahost,$this->chats->row['userid'],$this->chats->row['ID']);
                        if(!empty($this->chats->row['userid'])){

                        $storCtat[$this->chats->row['ID']] = array(date( "H:i", $this->chats->row['date'] ),$this->chats->row['username'],$redseahost,$this->chats->row['userid'],$this->chats->row['ID'],$colors[$this->chats->row['userid']%5]);
                        }
if(!empty($this->chats->row['userid'])){

                        $storCtat[$this->chats->row['ID']] = array(date( "H:i", $this->chats->row['date'] ),$this->chats->row['username'],$redseahost,$this->chats->row['userid'],$colors[$this->chats->row['userid']%5]);
                        }
}
ksort( $storCtat );
foreach ( $storCtat as $ChatLine )
{
  echo 
    "<div class=\"msgln\"><b class=\"player d-flex\" >
        <a style=\"color:".$ChatLine[5]. "!important;\" href=\"profile.php?uid=".$ChatLine[3]."\" target=\"_blank\">".
        $ChatLine[1]."</a> </b> <span class=\"msg\">".$ChatLine[2]."
        <span class=\"time-msg \">(".$ChatLine[0].")
        ";if($this->player->playerId == 1){
                echo "<a class='del' href='chat.php?del=".$ChatLine[4]."' >حذف</a>";
        }
        echo "
        </span></span><br>
    </div>";  
   // echo 
    // "<div class=\"msgln\"><b>
    //     <a class=\"player\" href=\"profile.php?uid=".$ChatLine[3]."\" target=\"_blank\">".
    //     $ChatLine[1]."</a>
    //     </b>: <span>".$ChatLine[2]."</span>
    //     <span class=\"time-msg \">(".$ChatLine[0].") </span><br>
    // </div>";
    //       echo 
    // "<div class=\"msgln\"><b class=\"player d-flex\" >
    //     <a style=\"color:".$ChatLine[4]. "!important;\" href=\"profile.php?uid=".$ChatLine[3]."\" target=\"_blank\">".
    //     $ChatLine[1]."</a> </b> <span class=\"msg\">".$ChatLine[2]."
    //     <span class=\"time-msg \">(".$ChatLine[0].") </span></span><br>
    // </div>";  
}
echo '</div>
<div>
<form name="message" action="">
  <input name="usermsg" class="text" type="text" id="usermsg" size="63" />
  <center><input name="submitmsg" type="button" id="submitmsg" value="';
echo LANGUI_CHAT_T2;
echo '" /></center>
</form>
</div>';
?>
</body>
</html>