<!DOCTYPE html>
<html lang="ar">
<head>



    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php


if (isset($_GET['terms'])) {
?>
<h1>قوانين اللعبة</h1>
لعبة عودة التتار هى مجرد لعبه للترفيه وتسلية الوقت وليس لاثارة المشاكل بين الناس او الخلافات او الخروج عن الاداب العامه لنا كمسلمين 
سوف يتم المحاسبه بكل حزم مع كل من يقوم بمخالفة الشروط الاتية:-</h5><p>
<b>#</b> ممنوع نشر او الاشهار لاى مواقع اخرى من خلال موقعنا عن طريق ارسال الرسائل او الكتابه بالوصف ومن يقوم بذلك يتم حظره نهائيا<br>
<b>#</b> من يقوم باستغلال خطا باللعبه لصالحه ضد اللاعبين وعدم تبليغ الاداره لحل المشكله يتم ايقاف اللاعب من فترة 72 ساعه الى ايقاف دائم على حسب الحالة<br>
<h3>حقوق كل لاعب :-</h3>
<b>#</b> للاعب الحق في الحصول على دعم مستمر والرد على مشاكله واستفسارته من خلال طاقم الاداة والرد على المشكله في مدة اقصاها 24 ساعه<br>
<b>#</b> للاعب الحق في الحصول على تعويض ان لحقت به اضرار ناتجه عن اخطاء اللعبه<br>
<h4>قوانين التعاملات المالية وشراء الذهب :-</h4>
كما نعرف فانه في عودة التتار يوجد تعاملات مالية وهى شراء الراغب من اللاعبين للذهب الخاص باللعبة لمنحه المزيد من الصلاحيات باللعبة 
وبما ان هناك تعاملات ماليه لابد من وجود قوانين تحكمها :-<p>
<b>#</b> في حال شراء اللاعب الذهب ولم يصل اليه عليه مراسلة الادارة برقم العمليه الشرائية التى لم تصل اليه حتى يتم التاكد منها من خلال الادارة<br>
<b>#</b> لا يحق للاعب بطلب ارجاع الاموال التى اشترى بها الذهب وقد وصل اليه الذهب بدون مشاكل او خلافات </h5>
<p>
يحق للادارة اللعبه بتغير هذه القوانين في اى وقت او الاضافه عليها وبمجرد تسجيلك في موقع عودة التتار سيكون هذا بمثابة الموافقه على هذه القوانين<p>

ادارة اللعبه<br>
<?php
}else {
?>
<h1><img src="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>x.gif" class="img_login" alt="تسجيل الدخول للعبه" /></h1>
<div align="center">
</a>
</div>
 <h5><img class="img_u04" src="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>x.gif" alt="التسجيل" /></h5>
<p><?php echo LANGUI_INDX_T3; ?></p>
<?php

       
if (isset($_GET['C4'])) {
echo date('Y/m/d H:i:s');
}
$m = new QueueModel();
$resultsb = $m->provider->fetchRow("SELECT end_date FROM p_queue WHERE id='3' and proc_type='57'");
$end_datesb = $resultsb["end_date"];

       
$fetchst = $m->provider->fetchRow("SELECT end_date FROM p_queue WHERE id='3' and proc_type='57'");
// Fetch row as associative array
$subtracted_date_st = $fetchst["end_date"];
       
$subtracted_st = date('Y-m-d H:i:s', strtotime($fetchedst));

// calculate the difference in seconds between the subtracted date and now
$diff_in_seconds_st = strtotime($subtracted_date_st) - time();

// if the difference is negative, get the absolute value
$diff_in_seconds_st = abs($diff_in_seconds_st);

// calculate the remaining days, hours, minutes and seconds
$remaining_days_st = floor($diff_in_seconds_st / 86400);
$remaining_hours_st = floor(($diff_in_seconds_st % 86400) / 3600);
$remaining_minutes_st = floor(($diff_in_seconds_st % 3600) / 60);

// format the remaining time as a string
$remaining_time_st = sprintf('%02d:%02d:%02d', $remaining_days_st, $remaining_hours_st, $remaining_minutes_st);


if (strtotime($end_datesb) > time()) {
    ?>
    <center><span style="font-size:20px;">باقي على بدأ اللعب:</span>
    <span id="timer1" style="font-size: 22px; color: orange; font-weight: bold; text-shadow: 1px 1px #000;"><?php 
  echo "<b>$remaining_days_st</b> أيام و <b>$remaining_hours_st</b> ساعة و <b>$remaining_minutes_st</b> دقيقة</span></td>";
      ?></span>
    <?php
}
?>
  
<form action="login" method="post" name="login">
<table cellpadding="1" cellspacing="1" id="login_form">
<tbody>
<tr class="top"><th><?php echo LANGUI_INDX_T1; ?> :</th><td><input class="text" name="name" type="text" title="<?php echo LANGUI_INDX_T1;  ?>" value="<?php   echo $this->name; ?>"><span class="error"><?php echo $this->err[0]; ?></span></td></tr>
<tr class="btm"><th><?php echo LANGUI_INDX_T2; ?> :</th><td><input class="text" name="password" type="password" title="<?php echo LANGUI_INDX_T2;  ?>" value="<?php   echo $this->password;  ?>" /><span class="error"><?php echo $this->err[1]; ?></span></td></tr>
</tbody>
</table>
<p class="btn"><input id="btn_login" class="dynamic_img" type="image" alt="????" src="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>x.gif" name="s1" value="anmelden">
<span class="error"> <?php if ($this->error != "") { echo $this->error; } ?></span>
</form>

<div align="center">
	</div>

<table border="0" cellspacing="0" cellpadding="0">

<tbody><tr class="top">
<th><strong>عدد اللاعبين:</strong></th>
<td><?php echo $this->data['players_count']; ?></td>
</tr>
<tr>
<th><strong>اللاعبون النشطون:</strong></th>
<td><?php echo $this->data['active_players_count']; ?></td>
</tr>
</tbody></table>
<br>
<table border="0" cellspacing="0" cellpadding="0">
<?php

$islamLover = new QueueModel();
$reset = $islamLover->provider->fetchRow("SELECT end_date FROM p_queue WHERE proc_type='25'");
$this->appConfig['system']['reset'] = date('Y/m/d H:i:s',strtotime($reset['end_date']));

$resultbs = $islamLover->provider->fetchRow("SELECT end_date FROM p_queue WHERE id='1' and proc_type='24'");
// Fetch row as associative array
$end_datebs = $resultbs["end_date"];

$redseahost = $this->appConfig['system']['server_days'];
// Subtract 10 days from the end date
$subtracted_date = date('Y-m-d H:i:s', strtotime("-$redseahost days", strtotime($end_datebs)));

// calculate the difference in seconds between the subtracted date and now
$diff_in_seconds = strtotime($subtracted_date) - time();

// if the difference is negative, get the absolute value
$diff_in_seconds = abs($diff_in_seconds);

// calculate the remaining days, hours, minutes and seconds
$remaining_days = floor($diff_in_seconds / 86400);
$remaining_hours = floor(($diff_in_seconds % 86400) / 3600);
$remaining_minutes = floor(($diff_in_seconds % 3600) / 60);

// format the remaining time as a string
$remaining_time = sprintf('%02d:%02d:%02d', $remaining_days, $remaining_hours, $remaining_minutes);


$islamLover = new QueueModel();
///// TATAR COUNTER
$fetchtatar = $islamLover->provider->fetchRow("SELECT end_date FROM p_queue WHERE id='1' and proc_type='24'");
// Fetch row as associative array
$fetchedtatar = $fetchtatar["end_date"];

$subtracted_tatar = date('Y-m-d H:i:s', strtotime($fetchedtatar));

// calculate the difference in seconds between the subtracted date and now
$diff_in_tatar = strtotime($subtracted_tatar) - time();

// if the difference is negative, get the absolute value
$diff_in_tatar = abs($diff_in_tatar);

// calculate the remaining days, hours, minutes and seconds
$remaining_days_t = floor($diff_in_tatar / 86400);
$remaining_hours_t = floor(($diff_in_tatar % 86400) / 3600);
$remaining_minutes_t = floor(($diff_in_tatar % 3600) / 60);

// format the remaining time as a string
$remaining_time_t = sprintf('%02d:%02d:%02d', $remaining_days_t, $remaining_hours_t, $remaining_minutes_t);
      
       
       
       
$islamLover = new QueueModel();
///// ARTS COUNTER
$fetcharts = $islamLover->provider->fetchRow("SELECT end_date FROM p_queue WHERE id='2' and proc_type='26'");
// Fetch row as associative array
$fetchedarts = $fetcharts["end_date"];

$subtracted_arts = date('Y-m-d H:i:s', strtotime($fetchedarts));

// calculate the difference in seconds between the subtracted date and now
$diff_in_arts = strtotime($subtracted_arts) - time();

// if the difference is negative, get the absolute value
$diff_in_arts = abs($diff_in_arts);

// calculate the remaining days, hours, minutes and seconds
$remaining_days_arts = floor($diff_in_arts / 86400);
$remaining_hours_arts = floor(($diff_in_arts % 86400) / 3600);
$remaining_minutes_arts = floor(($diff_in_arts % 3600) / 60);

// format the remaining time as a string
$remaining_time_arts = sprintf('%02d:%02d:%02d', $remaining_days_arts, $remaining_hours_arts, $remaining_minutes_arts);
       
///// RESET COUNTER
$fetchreset = $islamLover->provider->fetchRow("SELECT end_date FROM p_queue WHERE proc_type='25'");
// Fetch row as associative array
$fetchedreset = $fetchreset["end_date"];

$subtracted_reset = date('Y-m-d H:i:s', strtotime($fetchedreset));

// calculate the difference in seconds between the subtracted date and now
$diff_in_reset = strtotime($subtracted_reset) - time();

// if the difference is negative, get the absolute value
$diff_in_reset = abs($diff_in_reset);

// calculate the remaining days, hours, minutes and seconds
$remaining_days_reset = floor($diff_in_reset / 86400);
$remaining_hours_reset = floor(($diff_in_reset % 86400) / 3600);
$remaining_minutes_reset = floor(($diff_in_reset % 3600) / 60);

// format the remaining time as a string
$remaining_time_reset = sprintf('%02d:%02d:%02d', $remaining_days_reset, $remaining_hours_reset, $remaining_minutes_reset);
       
       
       
       
       $m = new QueueModel();
$updates =  $m->provider->fetchRow("SELECT end_date FROM p_queue WHERE proc_type='57' and id='3'");
$updatesok = $updates['end_date'];
       
$updatesreset =  $m->provider->fetchRow("SELECT end_date FROM p_queue WHERE proc_type='25'");
$updatesokreset = $updatesreset['end_date'];
       
if ($updatesokreset != null){  
 $m->provider->executeQuery2("UPDATE p_queue SET proc_type='57' WHERE id='3' and proc_type='26'");
}

if (!empty($updatesreset['end_date'])) {
?>
 <tbody><tr class="btm">
        <th>
            <strong>بقى على إعادة السيرفر:</strong>
        </th>
        <td><span id="timer2"><?php 
  echo "<b>$remaining_days_reset</b> أيام و <b>$remaining_hours_reset</b> ساعة و <b>$remaining_minutes_reset</b> دقيقة</span></td>";
?>
  </tr>
<?php
}else {

?>
    <tbody><tr class="top">
        <th>
            <strong>بدأ السيرفر منذ:</strong>
        </th>
        <td><span id="timer2">
          
    <?php 
  if (!empty($resultbs['end_date'])) {
  if ($updates == NULL){
  echo "<b>$remaining_days</b> أيام و <b>$remaining_hours</b> ساعة و <b>$remaining_minutes</b> دقيقة</span></td>";
  
  }
  
  else if ($updates != NULL){
echo "<font color='red'><b>لم يبدأ السيرفر بعد</b></font></span></td>";
  }
  }
  else
{
  echo "<font color='red'>الجولة محسومة تم نزول التتار</font></span></td>";									
  }
          ?>

    </tr>
    <tr >
        <th>
            <strong>سيتم نزول التحف بعد:</strong>
        </th>
<?php if (strtotime($fetchedarts) > time()) {
?>        <td><span id="timer1">
      
      
      <?php 
                                 
  echo "<b>$remaining_days_arts</b> أيام و <b>$remaining_hours_arts</b> ساعة و <b>$remaining_minutes_arts</b> دقيقة</span></td>";

          } else {
?>
      <td><span style="color: #ff0000;">تم نزول التحف</span></td>
      <?php
}
?>
    </tr>
<tr class="btm">
        <th>
            <strong>سيتم نزول التتار بعد:</strong>
        </th>
<?php if (strtotime($fetchedtatar) > time()) {
?>       
        <td><span id="timer1">
<?php 
  echo "<b>$remaining_days_t</b> أيام و <b>$remaining_hours_t</b> ساعة و <b>$remaining_minutes_t</b> دقيقة</span></td>";
     
} else {
            
?>
          
          <td><span style="color: #ff0000;">تم نزول التتار</span></td>
          
          <?php
  }
          ?>
    </tr>

	<table border="0" cellspacing="0" cellpadding="0">

<tbody><tr class="top">
<th><strong><span style="color: #ff0000;">مدة السيرفر :</span></strong></th>
<td><?php echo $GLOBALS['AppConfig']['system']['moda']; ?> يوم</td>
</tr>
<tr>
<th><strong><span style="color: #ff0000;">سرعة السيرفر :</span></strong></th>
<td>X<?php echo $GLOBALS['AppConfig']['Game']['speed']; ?></td>
</tr>
</tbody></table>
<?php } ?>
</tbody></table>
<?php } ?>
</body>
</html>