<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php

echo "</b><h1>";
echo LANGUI_LOGOUT_T1;
echo "</h1>\r\n<img class=\"roman\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"\">\r\n<p>";
echo LANGUI_LOGOUT_T2;
echo "</p>\r\n<p></p>\r\n\r\n<p>";
echo LANGUI_LOGOUT_T3;
echo "</p><br>\r\n<a href=\"login?dcookie\">";
echo LANGUI_LOGOUT_T4;
echo "</a>\r\n<p></p>";

?>
</body>
</html>