<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php 
$q                      = new QueueModel();
$get_num_loooting = $q->provider->fetchScalar('SELECT COUNT(*) FROM p_looting WHERE pid="'.$this->player->playerId.'" ');
?>
<h1>قائمة المزارع <span style="color:#C0C0C0;" class="info">(<?php echo $this->num_farm; ?>/<span style="color:#000;" class="info"><?php echo $get_num_loooting;?></span>)</span></h1>
<div id="textmenu">
<a href="looting" <?php if (!isset ($_GET['t'])) {?>class="selected"<?php } ?>>قائمة المزارع</a> | 
<a href="looting?t=1" <?php if ($_GET['t'] == 1) {?>class="selected"<?php } ?>>النهب التلقائي</a> | 
<a href="looting?t=4" <?php if ($_GET['t'] == 4) {?>class="selected"<?php } ?> >إضافة قرى لاعب</a>  |
<a href="travianar.php?t=3" <?php if ($_GET['t'] == 7) {?>class="selected"<?php } ?> >اضافه واحات</a>

</div>

<?php 
if (isset ($_GET['edit'])) {
$q                      = new QueueModel();
$edit = intval($_GET['edit']);
$get_edit = $q->provider->fetchRow("SELECT * FROM p_looting WHERE id='".$edit."' AND pid='".$this->player->playerId."'");
?>
<form action="" method="post">
<table cellspacing="1" cellpadding="1" id="coords">
<tbody><tr>
<td class="1439345654">
<div class="option" style="padding: 12px;">
<?php
                                        $t2_arr = explode( ',', $get_edit['troops'] );
                                        foreach( $t2_arr as $t2_str ) {
                                                $t = explode( ' ', $t2_str );
                                                        $troops [ $t[0] ] = $t[1];
                        }
switch($this->data['tribe_id']){
        case 1:
                $farmTroops = array(1,2,3,5,6);
                break;
        case 2:
                $farmTroops = array(11,12,13,15,16);
                break;
        case 3:
                $farmTroops = array(21,22,24,25,26);
                break;
        case 6:
                $farmTroops = array(51,52,53,55,56);
                break;
      case 7:
                $farmTroops = array(100,101,102,104,105);
                break;
}
foreach($farmTroops as $tid){
foreach($troops as $troopId=>$troopNum){
        if($tid == $troopId){$num = $troopNum;}
}
?><label><input type="text" value="<?php echo $num; ?>" name="t[<?php echo $tid; ?>]" class="text" style="width:10%"> <img class="unit u<?php echo $tid; ?>" src="core-f/style-f/x.gif" alt="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>" title="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>"> <?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?></label><br><?php } ?>
</td>
</tr>
</tbody></table>
<button type="submit" value="تعديل" name="s1" id="btn_ok"><div class="button-container"><div class="button-position"><div class="btl"><div class="btr"><div class="btc"></div></div></div><div class="bml"><div class="bmr"><div class="bmc"></div></div></div><div class="bbl"><div class="bbr"><div class="bbc"></div></div></div></div><div class="button-contents">تعديل</div></div></button></form>
<?php

}else 
if($this->selectedTabIndex == 5){ 
if (($this->data['num_farm']+200) < 750) {
?>
<form method="POST" action="looting?dellall">
<h4>زيادة عدد المزارع </h4>
العدد الحالي : <?php echo $this->num_farm; ?> ، هل تريد <a href="looting?addfarm">زياده 50 مزرعه</a> مقابل <?php echo ($this->num_farm/200)*250; ?> <img src="core-f/style-f/gold.gif" title="الذهب" class="1.410472499E+13 1453480888">
</form>
<?php
}else { 
echo "لقد وصلت الى الحد الاقصى من عدد المزارع ، شكرا لك";
}
}else
if($this->selectedTabIndex == 4){ 
?>
<form method="POST" action="looting?t=2&allv">
<h4>اضافه قراك الى قائمه المزارع </h4>
<div class="option" style="padding: 12px;">
<?php 
$t_arr = explode( '|', $this->data['troops_num'] );
                        foreach( $t_arr as $t_str ) {
                                $t2_arr = explode( ':', $t_str );
                                if ( $t2_arr[0] == -1 ) {
                                        $t2_arr = explode( ',', $t2_arr[1] );
                                        foreach( $t2_arr as $t2_str ) {
                                                $t = explode( ' ', $t2_str );
                                                if ( $t[0] == 4 || $t[0] == 7 || $t[0] == 8 || $t[0] == 9 || $t[0] == 10 
                                                  || $t[0] == 14 || $t[0] == 17 || $t[0] == 18 || $t[0] == 19 || $t[0] == 20 
                                                  || $t[0] == 23 || $t[0] == 27 || $t[0] == 28 || $t[0] == 29 || $t[0] == 30 || $t[0] == 99
                                                  || $t[0] == 54 || $t[0] == 57 || $t[0] == 58 || $t[0] == 59 || $t[0] == 60 ){
                                                        continue;
                                                }
                                                        $troops [ $t[0] ] = $t[1];
                                        }
                                }
                        }
switch($this->data['tribe_id']){
        case 1:
                $farmTroops = array(1,2,3,5,6);
                break;
        case 2:
                $farmTroops = array(11,12,13,15,16);
                break;
        case 3:
                $farmTroops = array(21,22,24,25,26);
                break;
        case 6:
                $farmTroops = array(51,52,53,55,56);
                break;
      case 7:
                $farmTroops = array(100,101,102,104,105);
                break;
}
foreach($farmTroops as $tid){
foreach($troops as $troopId=>$troopNum){
        if($tid == $troopId){$num = $troopNum;}
}
?><label><input type="text" value="0" name="t[<?php echo $tid; ?>]" class="text" style="width:10%"> <img class="unit u<?php echo $tid; ?>" src="core-f/style-f/x.gif" alt="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>" title="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>"> <b><?php echo $num; ?></b> <?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?></label><br><?php } ?>
</div>
<table cellspacing="1" cellpadding="1" id="coords">
	<tbody>
		<tr>
			<td></td>
		</tr>
		<tr>
			<td class="target"><span>اسم اللاعب:</span><input type="text"  size = "50" value="" name="p_name" class="text"> </td>
		</tr>
	</tbody>
</table>
<div style="float:right;margin-top:10px;">
<button type="submit" value="اضافة مزرعة" name="s1" id="btn_ok"><div class="button-container"><div class="button-position"><div class="btl"><div class="btr"><div class="btc"></div></div></div><div class="bml"><div class="bmr"><div class="bmc"></div></div></div><div class="bbl"><div class="bbr"><div class="bbc"></div></div></div></div><div class="button-contents">اضافة مزرعة</div></div></button>
</div>
<?php
}else 
if($this->selectedTabIndex == 0){ 
?>
<script src="core-f/style-f/js/jquery.js" type="text/javascript"></script>
<script>var texting = "يرجى الانتظار بينما يتم الهجوم";</script>
<script type="text/javascript" src="core-f/style-f/js/secretfarmjs.js"></script>
<div id="farming"></div><br>
<form name='farm'>
<table id="plusFunctions" cellpadding="1" cellspacing="1"><thead>
<th colspan="8">قائمة المزارع</th>
<tr>
     <td style="width: 1%"><input id="clickall" type='checkbox' onclick='CheckAll(this.checked)'></td>    
     <td style="width: 30%">الاسم</td>
     <td style="width: 1%">السكان</td>
     <td style="width: 22%">اللاعب</td>
     <td style="width: 15%">التحالف</td>
     <td style="width: 30%">الجيش</td>
     <td style="width: 1%">تعديل</td>
     <td style="width: 1%"><a href="looting?delall"><img src="core-f/style-f/x.gif" class="del tooltip2" title="حذف جميع المزارع"></a></td>
</tr>
</thead><tbody>

<?php
$start = 0;
if($this->data['tribe_id'] == 2)
{
$start = 10;
}
if($this->data['tribe_id'] == 3)
{
$start = 20;
}
if($this->data['tribe_id'] == 6)
{
$start = 50;
}
if($this->data['tribe_id'] == 7)
{
$start = 99;
}
if($this->data['tribe_id'] == 8)
{
$start = 60;
}
if($this->data['tribe_id'] == 9)
{
$start = 70;
}

$q2 = new QueueModel();
$ii = 0;
while ($this->get_looting->next ())
{
$ii += 1;
$t = true;
$vid= $q2->provider->fetchRow("SELECT village_name,player_name,player_id,alliance_id,alliance_name,people_count FROM p_villages WHERE id='".$this->get_looting->row['avid']."'");
$troop = explode('=', $this->get_looting->row['troops']);
if ($vid['village_name'] == '') {
$vname = 'واحة';
$pp = "-";
}else {
$vname = $vid['village_name'];
$pp = $vid['people_count'];
}
$pname = ($vid['player_name'] == "") ? "-" : "<a href='profile?uid=".$vid['player_id']."'>".$vid['player_name']."</a>";
$pl = ($vid['alliance_name'] == "") ? "-" : "<a href='alliance?id=".$vid['alliance_id']."'>".$vid['alliance_name']."</a>";
?>
<tr>
<?php echo "<td id='a".$ii."'><center><input class='check' type='checkbox' name='list[]' id='list' value='".$this->get_looting->row['avid']."|".$this->get_looting->row['x']."|".$this->get_looting->row['y']."|".($start+$troop[0])."|".$this->get_looting->row['troops']."|".md5(md5(md5($this->data['farming'].$this->get_looting->row['avid'])))."'></center></td>"; ?>
     <td id='b<?php echo $ii; ?>'><a href='village3?id=<?php echo $this->get_looting->row['avid']; ?>'> (<?php echo $this->get_looting->row['x']; ?>|<?php echo $this->get_looting->row['y']; ?>) <?php echo $vname; ?></a></td>
     <td id='c<?php echo $ii; ?>'><center><?php echo $pp; ?></center></td>
     <td id='d<?php echo $ii; ?>'><center><?php echo $pname; ?></center></td>
     <td id='f<?php echo $ii; ?>'><center><?php echo $pl; ?></center></td>
     <td id='g<?php echo $ii; ?>'><center>
<?php 
$test = $this->get_looting->row['troops'];
$t2_arr = explode (',', $test);
foreach ($t2_arr as $t2_str)
{
$t = explode (' ', $t2_str);
if ($t[1] <= 0) {
continue;
}
?><img class='unit u<?php echo $t[0]; ?>' src='core-f/style-f/x.gif'> <?php echo $t[1];
}

?>
</center></td>
     <td id='e<?php echo $ii; ?>'><center><a href='looting?t=3&edit=<?php echo $this->get_looting->row['id']; ?>'>تعديل</a></center></td>
     <td id='t<?php echo $ii; ?>'><center><a href='looting?del=<?php echo $this->get_looting->row['id']; ?>'><img class='del' src='core-f/style-f/x.gif'></a></center></td>
</tr>

<?php
}
if(!$t)
{
     echo '<tr><td colspan="8"><center>'.LANGUI_FARM_T4.'</center></td></tr>';
}

?>
</tbody>
</table><p>
<input class="text" id="linkToClick" name="attack" type="button" value="هجوم " onClick="javascript:farming();scrollTo(0,0);">
</form>
<script language="JavaScript">
    document.onkeypress = function (event) {
        event = (event || window.event);
        if (event.keyCode == 32) {
            return false;
        }
    }
    document.onmousedown = function (event) {
        event = (event || window.event);
        if (event.keyCode == 32) {
            return false;
        }
    }
document.onkeydown = function (event) {
        event = (event || window.event);
        if (event.keyCode == 32) {
            return false;
        }
    }
</script>
 
 

<?php
if (isset ($_GET['automatic'])) {
$q = new QueueModel();
$get_num_loooting = $q->provider->fetchScalar('SELECT COUNT(*) FROM p_looting WHERE pid="'.$this->player->playerId.'"');
$time = ($get_num_loooting*8);
 
?>
<script>
  document.getElementById('clickall').click();
  document.getElementById('linkToClick').click();
</script>
<?php
echo "سيتم الهجوم مره اخر بعد  <b><span id=\"timer1\">".WebHelper::secondstostring( $time )."</span></b>";
}
?>
 
<?php } elseif($this->selectedTabIndex == 1){ ?>
<p>
    <b>طريقة العمل</b>
    </p>
    <li>قم بفتح <a href="looting?automatic" target="_blank" class="1.40947860409E+13">هذه الصفحة</a> في نافذة جديدة ولا تغلقها ابداً.</li>
    <li>اذا كنت تملك اكثر من قرية لا تتنقل بينها حتى لا يتوقف النهب.</li>
<p></p>
 
<br><br>
<?php } elseif($this->selectedTabIndex == 2){
$start = 0;
if($this->data['tribe_id'] == 2)
{
$start = 10;
}
if($this->data['tribe_id'] == 3)
{
$start = 20;
}
if($this->data['tribe_id'] == 6)
{
$start = 50;
}
if($this->data['tribe_id'] == 7)
{
$start = 99;
}
if($this->data['tribe_id'] == 8)
{
$start = 60;
}
if($this->data['tribe_id'] == 9)
{
$start = 70;
}
?>
<span class="error"><?php echo $this->error; ?></span>
<form method="POST" action="looting?t=2">
<h4>اضافة مزرعة جديدة</h4>
<table cellspacing="1" cellpadding="1" id="coords">
<tbody><tr>
<td>
<div class="option" style="padding: 12px;">
<?php 
$t_arr = explode( '|', $this->data['troops_num'] );
                        foreach( $t_arr as $t_str ) {
                                $t2_arr = explode( ':', $t_str );
                                if ( $t2_arr[0] == -1 ) {
                                        $t2_arr = explode( ',', $t2_arr[1] );
                                        foreach( $t2_arr as $t2_str ) {
                                                $t = explode( ' ', $t2_str );
                                                if ( $t[0] == 4 || $t[0] == 7 || $t[0] == 8 || $t[0] == 9 || $t[0] == 10 
                                                  || $t[0] == 14 || $t[0] == 17 || $t[0] == 18 || $t[0] == 19 || $t[0] == 20 
                                                  || $t[0] == 23 || $t[0] == 27 || $t[0] == 28 || $t[0] == 29 || $t[0] == 30 || $t[0] == 99
                                                  || $t[0] == 54 || $t[0] == 57 || $t[0] == 58 || $t[0] == 59 || $t[0] == 60 ){
                                                        continue;
                                                }
                                                        $troops [ $t[0] ] = $t[1];
                                        }
                                }
                        }
switch($this->data['tribe_id']){
        case 1:
                $farmTroops = array(1,2,3,5,6);
                break;
        case 2:
                $farmTroops = array(11,12,13,15,16);
                break;
        case 3:
                $farmTroops = array(21,22,24,25,26);
                break;
        case 6:
                $farmTroops = array(51,52,53,55,56);
                break;
      case 7:
                $farmTroops = array(100,101,102,104,105);
                break;
}
foreach($farmTroops as $tid){
foreach($troops as $troopId=>$troopNum){
        if($tid == $troopId){$num = $troopNum;}
}
?><label><input type="text" value="0" name="t[<?php echo $tid; ?>]" class="text" style="width:10%"> <img class="unit u<?php echo $tid; ?>" src="core-f/style-f/x.gif" alt="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>" title="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>"> <b><?php echo $num; ?></b> <?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?></label><br><?php } ?>
</div>
</td>


<td>
<table cellspacing="1" cellpadding="1" id="coords">
	<tbody>
		<tr>
			<td></td>
		</tr>
		<tr>
			<td class="target"><span>X:</span><input type="text" maxlength="4" value="<?php echo $this->x; ?>" name="x" class="text"> <span>Y:</span><input type="text" maxlength="4" value="<?php echo $this->y; ?>" name="y" class="text"></td>
		</tr>
	</tbody>
</table>

</td>
</tr>
</tbody></table>
<div class="clear"></div>
<div style="float:right;margin-top:10px;">
<button type="submit" value="اضافة مزرعة" name="s1" id="btn_ok"><div class="button-container"><div class="button-position"><div class="btl"><div class="btr"><div class="btc"></div></div></div><div class="bml"><div class="bmr"><div class="bmc"></div></div></div><div class="bbl"><div class="bbr"><div class="bbc"></div></div></div></div><div class="button-contents">اضافة مزرعة</div></div></button>
</div>
<div class="clear"></div>
<br>
<div class="clear"></div>
<br>
<br>
</form>
<a href="looting?t=4" >اضف قرى لاعب </a>
<?php } elseif($this->selectedTabIndex == 3){ ?>
يجب عليك تفعيل خاصيه النهب المتطور من قائمة بلاس
<?php } 
?>
</body>
</html>