<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<script type="text/javascript">
                function payResources(id)
                {
                        var txt = _(id);
                        if (txt != null)
                        {
                                window.location = "plus?sil=" + txt.value;
                        }
                }
        </script>
<script type="text/javascript">
                function payResources1(id)
                {
                        var txt = _(id);
                        if (txt != null)
                        {
                                window.location = "plus?gol=" + txt.value;
                        }
                }
        </script><?php
$run = ($GLOBALS['AppConfig']['Game']['plus7_on']);
$run2 = 1;
$freegold=($GLOBALS['AppConfig']['Game']['setgold']);

echo "<h1><p>";
echo '<b>قائمة <font color="#71D000"> ب</font><font color="#FF6F0F">ل</font>ا<font color="#71D000">س</font></b>';
echo "</p></h1>\r\n<div id=\"textmenu\">\r\n   <a href=\"plus\"";
  if ($this->selectedTabIndex == 0 && !isset ($_GET['copon'])) {
      echo " class=\"selected\"";
  }
  echo ">";
  echo LANGUI_PLUS_T3;
  echo "</a>\r\n | <a href='plus?t=4' ";
if ($this->selectedTabIndex == 4) {
      echo " class=\"selected\"";
  }
echo ">المميزات</a> |  <a href=\"plus?t=2\"";
  if ($this->selectedTabIndex == 2) {
      echo " class=\"selected\"";
  }
  echo ">";
  echo LANGUI_PLUS_T5;
  echo "</a>\r\n | <a href=\"plus?t=3\"";
  if ($this->selectedTabIndex == 3) {
      echo " class=\"selected\"";
  }
  echo ">";
  echo LANGUI_INVITE_T1;
  echo "</a> | <a ";
if ($this->selectedTabIndex == 1) {
     echo " class=\"selected\"";
  }
echo "href='plus?copon' "; if (isset ($_GET['copon'])) {
     echo " class=\"selected\"";
  }
 echo "> </a>";//الكوبون

echo "  <a ";// |
if ($this->selectedTabIndex == 5) {
     echo " class=\"selected\"";
  }
echo "href='plus?t=5'>تحويل الذهب</a>";

if ($this->selectedTabIndex == 0 OR $this->selectedTabIndex == 6) {
?>
<?php
}
echo "</div>";
if (isset($_GET['copon'])) {
if ($this->player->playerId == 1) {
?>

<form method="post" action="" class="coupon-form">
  <div class="form-group">
    <label for="num_copons">عدد الكوبونات :</label>
    <input type="number" id="num_copons" name="num_copons" min="1" required>
  </div>
  <div class="form-group">
<label for="golden">كمية الذهب <img src="core-f/style-f/gold.gif"> :</label>
<input type="number" id="golden" name="golden" min="1" required>
  </div>
  <button type="submit" class="submit-button">انشأ مجموعة جديدة</button>
</form>
<br><br>
<style>
  .coupon-form {
    max-width: 400px;
    margin: auto;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 20px;
    border: 2px solid #ccc;
    border-radius: 5px;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
  }
  
  input {
    padding: 8px;
    border-radius: 5px;
    border: none;
    box-shadow: inset 1px 1px 3px rgba(0,0,0,0.3);
  }
  
  button {
    padding: 10px 20px;
    background-color: #008CBA;
    color: #fff;
    font-size: 16px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: all 0.3s ease-in-out;
  }
  
  button:hover {
    background-color: #006080;
    box-shadow: 1px 1px 5px rgba(0,0,0,0.5);
  }
</style>


<?php
}else {
?>
<form action="" method="post">
<table class="rate_details lang_rtl lang_ar" cellpadding="1" cellspacing="1">
        <thead>
            <tr>
                <th colspan="2">أذ كنت تملك كوبوناّ فأدخل الكود</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>كود الكوبون</td>
                <td><input type="text" maxlength="60" size="35" name="name" class="text"></td>
            </tr>
            </tbody>
    </table>
<center>
        <input type="image" value="" name="s1" id="btn_send" class="dynamic_img" src="core-f/style-f/x.gif" alt="ارسال" tabindex="4;">
    </center>
</form>

<?php
}

// ALL COPY RIGHTS RESERVED TO RED SEA HOST -- WWW.REDSEA-H.COM +962778984129
$tatarzx = new QueueModel();

if ($this->player->playerId == 1) {
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        $num_copons = intval($_POST['num_copons'] ?? 0);
        $golden = intval($_POST['golden'] ?? 0);

        $copons = array();

        for ($i = 0; $i < $num_copons; $i++) {
            do {
                $name = '';
                $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
                $n = 10;

                for ($j = 0; $j < $n; $j++) {
                    $index = mt_rand(0, strlen($characters) - 1);
                    $name .= $characters[$index];
                }
            } while ($tatarzx->provider->executeQuery('SELECT COUNT(*) FROM `copon` WHERE `name` = "'.$name.'"') > 0);

            $tatarzx->provider->executeQuery('INSERT INTO `copon`(`gold`, `name`) VALUES ("'.$golden.'","'.$name.'")');
            $copons[] = array('name' => $name, 'golden' => $golden);
        }
    }
?>

<table>
    <thead>
        <tr>
            <th>كود الكوبون</th>
            <th>كمية الذهب</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($copons as $copon) { ?>
            <tr>
                <td class="coupon-name"><?php echo $copon['name']; ?></td>
                <td><?php echo $copon['golden']; ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table><br>
<button class="copy-button" onclick="copyCouponNames()">قم بنسخ جميع الأكواد</button>

<script>
    function copyCouponNames() {
        const couponNames = document.querySelectorAll('.coupon-name');
        const couponNamesArray = Array.from(couponNames);
        const couponNamesString = couponNamesArray.map(couponName => couponName.textContent).join(' ');
        navigator.clipboard.writeText(couponNamesString);
    }
</script>

<?php 
}else {
if (isset($_POST['name'])) {
$name = htmlspecialchars($_POST['name']);
$nn = $tatarzx->provider->fetchScalar("SELECT COUNT(*) FROM copon WHERE name='".$name."'");
$sn = $tatarzx->provider->fetchRow("SELECT * FROM copon WHERE name='".$name."'");
if ($nn) {
require_once( MODEL_PATH 	. 'payment.php' );
$sssm = new PaymentModel();
$sssm->InsertMoneyLog( $name, $this->data['name'], $sn['gold'], 0, "USD", "cashu" );

		$tatarzx->provider->executeQuery( "UPDATE p_players p SET p.gold_num=gold_num+%s WHERE p.id='%s'", array(
            $sn['gold'],
			$this->player->playerId
        ) );
require_once( MODEL_PATH."payment.php" );
$mpc = new PaymentModel();
$mpc->InsertMoneyLog( "كوبون", $this->data['name'], $sn['gold'], $cost, $currency, $time, $type );

		$tatarzx->provider->executeQuery("DELETE FROM copon WHERE name='%s'", array(
            $name
        ));
echo '<span class="error">تم شحن '.$sn['gold'].' بحسابك</span>';
}else {
echo '<span class="error">رقم الكوبون خاطئ</span>';
}
}
}


}else
if ($this->selectedTabIndex == 6) {
?>
<?php 
echo '</td></tr></table></center>';
 }
  else
  if ($this->selectedTabIndex == 0) {
      if ($this->packageIndex < 0) {
          echo "<div id=\"products\">\r\n\t";
          $_c = 0;
          foreach ($GLOBALS['AppConfig']['plus']['packages'] as $package) {
              ++$_c;
              echo "\t<table class=\"product lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t\t<thead>\r\n\t\t\t<tr><th>";
              echo $package['name'];
              echo "</th></tr>\r\n\t\t</thead>\r\n        <tbody>\r\n\t\t\t<tr><td class=\"pic\"><a href=\"?id=";
              echo $_c;
              echo "\"><img src=\"core-f/style-f/default/plus/";
              echo htmlspecialchars($package['image']);
              echo "\" style=\"width:100px;height:100px;\" alt=\"";
              echo htmlspecialchars($package['name']);
              echo "\"></a></td></tr>\r\n            <tr><td><s>";
              echo $package['gold'];
              echo "&nbsp;</s>";
              echo "</a></td></tr>\r\n            <tr><td>";
              echo $package['goldplus'];
              echo "&nbsp;";
              echo LANGUI_PLUS_T6;
              echo "</td></tr> <tr><td>";
if ($package['plus'] != 0) {
              echo "زياده ".$package['plus']."%";
}else {
              echo "لايوجد زياده";
}
              echo "</td></tr>\r\n            <tr><td>";
              echo $package['cost'];
              echo "&nbsp;";
              echo $package['currency'];
			  echo "</td></tr>\r\n            <tr><td>";
              echo $package['cost']*3.75;
              echo "&nbsp;";
              echo "ريال";
              echo "</td></tr> \r\n\t\t\t<tr><td><a class='signUpButton' href=\"?id=";
              echo $_c;
              echo "\">";
              echo LANGUI_PLUS_T7;
               echo "</a><br/> <!--<a onclick='__PayNow(\"pay\" , ".($_c-1).")' >PayLink</a> <br/> <a onclick='__PayNow(\"apple\" , ".($_c-1).")' >Apple Pay</a>--></td></tr>\r\n\t\t</tbody>\r\n\t</table>\r\n\t";
          }
if ( ($this->appConfig['system']['copon'] = 1)){  
?>
<table class="product lang_rtl lang_ar" cellpadding="1" cellspacing="1">
		<thead>
			<tr><th>الكوبون</th></tr>
		</thead>
        <tbody>
			<tr><td class="pic"><a href="?copon"><img src="core-f/style-f/default/plus/package_co.webp" style="width:100px;height:100px;" alt="كوبون الذهب" title="كوبون الذهب"></a></td></tr>
            <!--<tr><td>-</td></tr>
            <tr><td>-</td></tr>-->
			<tr><td><a class="signUpButton" href="?copon">» ادخل الكود</a></td></tr>
		</tbody>
	</table>
	<table class="product lang_rtl lang_ar" cellpadding="1" cellspacing="1">
		<thead>
			<tr><th>ذهب مجانى !</th></tr>
		</thead>
        <tbody>
			<tr><td class="pic"><a href="links"><img src="core-f/style-f/default/plus/f7bcc57146b2c3893e07864f56332a29.webp" style="width:100px;height:100px;" alt="ذهب مجانى !" title="ذهب مجانى !"></a></td></tr>
            <!--<tr><td>-</td></tr>
            <tr><td>-</td></tr>-->
			<tr><td><a class="signUpButton" href="links">انشر و إكسب</a></td></tr>
		</tbody>
	</table>
<?php
}
          echo "\t<div class=\"clear\"></div>\r\n</div>\r\n";
?>

<?php
require_once( MODEL_PATH."payhis.php" );
$mas = new QueueModel();
$nam = $this->data['name'];
$this->dataList = $mas->provider->fetchResultSet('SELECT * FROM money_log WHERE usernam="'.$nam.'"');
$found = false;
$k = 0;
while ($this->dataList->next()) {
$found = true;
$k++;

?>
<?php
}
if (!$found) {
?>
<tr><td class="none" colspan="5"><center>لايوجد عمليات شرائيه مرتبطه في حسابك</center></td></tr>
<?php
}

?>
<div style="padding: 10px 10px; color: red; font-size: 10px;"><i>عندما ينتهي السيرفر ينتقل الذهب الى السيرفر الجديد تلقائيا فور تسجيلك عبر الايميل</i></div>
<?php

      } else {
          $_c = 0;

          
?>
<?php
          foreach ($GLOBALS['AppConfig']['plus']['payments'] as $paymentKey => $payment ) {
              ++$_c;
              
              if ($this->appConfig['plus']['packages'][$this->packageIndex]['name'] == 'sms') {
              if ($paymentKey != 'payGol') {
              continue;
              }
              }
              if ($this->appConfig['plus']['packages'][$this->packageIndex]['name'] != 'sms') {
              if ($paymentKey == 'payGol') {
              continue;
              }
              }
if (($this->appConfig['plus']['packages'][$this->packageIndex]['sawacost'] ?? 0) == 0) {
if($payment['image'] == 'sawa' or $payment['image'] == 'mobily') {
              continue;
}
}
              echo "<table class=\"rate_details lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n    <thead>\r\n        <tr><th colspan=\"2\">";
              echo $_c . ". " . $payment['name'];
              echo "</th></tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr>\r\n            <td class=\"pic\">\r\n\t\t\t\t<img src=\"core-f/style-f/default/plus/";
              echo htmlspecialchars($GLOBALS['AppConfig']['plus']['packages'][$this->packageIndex]['image']);
              echo "\" style=\"width:100px;height:100px;\" alt=\"";
              echo htmlspecialchars($GLOBALS['AppConfig']['plus']['packages'][$this->packageIndex]['name']);
              echo "\">\r\n                <div>";
              echo text_period_lang;
              echo ": ";
              $periodConst = "payments_" . $paymentKey . "_period";
              echo defined($periodConst) ? constant($periodConst) : '';
              echo "</div>\r\n            </td>\r\n            <td class=\"desc\">\r\n                ";
              $descConst = "payments_" . $paymentKey . "_description";
              echo defined($descConst) ? constant($descConst) : '';
              echo "<p>\r\n                <a href=\"#\" onclick=\"window. open('payment.php?p=";
              echo $paymentKey;
              echo "&pg=";
              echo $this->packageIndex;
              echo "','tgpay','scrollbars=yes,status=yes,resizable=yes,toolbar=yes,width=800,height=600');return false;\">\r\n                <img src=\"core-f/style-f/default/plus/";
              echo htmlspecialchars($payment['image']);
$widthy = 0;
if($payment['image'] == 'sawa' or $payment['image'] == 'mobily') {
echo $this->appConfig['plus']['packages'][$this->packageIndex]['sawacost'].".webp";
if($payment['image'] == 'mobily') {
if($this->appConfig['plus']['packages'][$this->packageIndex]['sawacost'] == '20') {
$widthy = 20;
}
if($this->appConfig['plus']['packages'][$this->packageIndex]['sawacost'] == '50') {
$widthy = 50;
}
if($this->appConfig['plus']['packages'][$this->packageIndex]['sawacost'] == '100') {
$widthy = 100;
}
}
}
switch ($widthy) {
    case 20:
        echo "\" style=\"width:280px; height:73px;\" alt=\"";
        break;
    case 50:
        echo "\" style=\"width:280px; height:194px;\" alt=\"";
        break;
    case 100:
        echo "\" style=\"width:280px; height:73px;\" alt=\"";
        break;
}
if($widthy == 0) {
            echo "\" style=\"width:119px; height:58px;\" alt=\"";
}
              echo htmlspecialchars($payment['name']);
              echo "\"></a>";
?>
</td>






<?php
echo "</tr>\r\n   ";
?>

<?php
echo " </tbody>\r\n</table>\r\n";
          
      }
}
  } else if ($this->selectedTabIndex == 2) {
      echo "<p>";
      if (0 < $this->data['gold_num']) {
          echo LANGUI_PLUS_T30;
          echo "<b> ";
          echo $this->data['gold_num'];
          echo "</b> ";
          echo LANGUI_PLUS_T31;
echo ".";
      } else {
          echo LANGUI_PLUS_T32;
echo ".";
      }
?>


<?php
$this->page = isset( $_GET['s'] ) && is_numeric( $_GET['s'] ) && 0 <= intval( $_GET['s'] ) && intval( $_GET['s'] ) <= 1 ? intval( $_GET['s'] ) : 0;
?>
<hr>
<div id="textmenu">
    <a href="plus.php?t=2&s=0" class="<?php echo ($this->page == 0) ? "selected" : "";?>">الموارد</a> | 
    <a href="plus.php?t=2&s=1" class="<?php echo ($this->page == 1) ? "selected" : "";?>">الجيوش</a>
</div>


<?php
if ($this->page == 0) {
      echo "</p>\r\n<table class=\"plusFunctions\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
      echo "وظائف بلاس";
      echo "</th></tr>\r\n\t\t<tr><td></td><td>";
      echo LANGUI_PLUS_T34;
      echo "</td><td>";
      echo text_period_lang;
      echo "</td><td>";
      echo LANGUI_PLUS_T2;
      echo "</td><td>";
      echo LANGUI_PLUS_T35;
      echo "</td></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,0);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t<p><b><font color=\"#71D000\"> ";
      echo LANGUI_PLUS_T36;
      echo "  </p><br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">";
      echo $this->getRemainingPlusTime(0);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[0]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[0]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[0]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(0);
      echo "</td>\r\n\t\t</tr>\t\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"5\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,1);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r1\" src=\"core-f/style-f/x.gif\" alt=\"";
      echo item_title_1;
      echo "\" title=\"";
      echo item_title_1;
      echo "\"> ";
      echo LANGUI_PLUS_T39;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">";
      echo $this->getRemainingPlusTime(1);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[1]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[1]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[1]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(1);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,2);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r2\" src=\"core-f/style-f/x.gif\" alt=\"";
      echo item_title_2;
      echo "\" title=\"";
      echo item_title_2;
      echo "\"> ";
      echo LANGUI_PLUS_T40;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">";
      echo $this->getRemainingPlusTime(2);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[2]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[2]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[2]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(2);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,3);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r3\" src=\"core-f/style-f/x.gif\" alt=\"";
      echo item_title_3;
      echo "\" title=\"";
      echo item_title_3;
      echo "\"> ";
      echo LANGUI_PLUS_T41;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">";
      echo $this->getRemainingPlusTime(3);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[3]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[3]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[3]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(3);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,4);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r4\" src=\"core-f/style-f/x.gif\" alt=\"";
      echo item_title_4;
      echo "\" title=\"";
      echo item_title_4;
      echo "\"> ";
      echo LANGUI_PLUS_T42;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">";
      echo $this->getRemainingPlusTime(4);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[4]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[4]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[4]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(4);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t";
	  
  
    
       $protection   = $GLOBALS['AppConfig']['Game']['protection'] - $GLOBALS['AppConfig']['Game']['numpro'];
      $uid = $this->player->playerId; 
               $up3= $this->queueModel->provider->fetchScalar('SELECT up3 FROM p_players WHERE id ="'.$this->player->playerId.'"');
      $gold_num = $this->queueModel->provider->fetchScalar('SELECT gold_num FROM p_players WHERE id ="'.$this->player->playerId.'"');

      $upes =  ($GLOBALS['AppConfig']['Game']['upes']) ;
     $JC_8_cost = $GLOBALS['AppConfig']['Game']['8_cost'] ;
      $new_reg_date= strtotime($this->dataGame['registration_date'] ?? 'now') + strtotime('-'. $protection .' hour') ;
      $registration_date = date('Y-m-d H:i:s', $new_reg_date);
      
      $u1= $this->queueModel->provider->fetchScalar( "SELECT COUNT(*) FROM `p_queue` WHERE  proc_type=24  " ); 

      
      if (((isset ($_GET['protic']) AND isset ($_GET['key'])) AND $_GET['key'] == $this->data['update_key']) AND $JC_8_cost  <= $gold_num AND $up3 < $upes AND $u1  >= 1  )
      {
      
      
      $shadi =  $JC_8_cost  ;
      
      $m = new QueueModel();
      $m->provider->executeQuery2("UPDATE p_players SET gold_num=gold_num-'".$shadi."' WHERE id = '".$this->player->playerId."'");
      $m->provider->executeQuery2("UPDATE p_players SET up3=up3+1 WHERE id = '".$this->player->playerId."'");
      $m->provider->executeQuery2("UPDATE p_players SET protection=1 WHERE id = '".$this->player->playerId."'");
      
            $m->provider->executeQuery2("UPDATE `p_players` SET `registration_date` ='". $registration_date ."' WHERE  `p_players`.`id` =$uid");

      
      echo '<meta http-equiv="REFRESH" content="0;url=plus.php?t=2">';
      
      }
      
  
  ?>
   </tr>
<form action="" method="get" class="range-examples" style="background:hsl(90,30%,95%)"></form>
<tr>
   <td class="man"><a href="#"><img class="help" src="core-f/style-f//x.gif"></a></td>
   <td class="desc 1482372422 1487796890"><b></b> حماية  <br><span class="run 1482372422 1487796890"><span id="timer1" class="1482372422 1487796890"></span></span>
      <font color="red">تم شراء : <? echo $up3; ?> من اصل <? echo $upes; ?></font>
   </td>
   <td class="cost 1482372422 1487796890">فورا</td>
   <td class="cost 1482372422 1487796890"><img src="core-f/style-f/x.gif" class="gold" width="15px" title="ذهب" class="1482372186 1487796890"> <?php echo $JC_8_cost * ($up3 + 2) ; ?></td>
   <td class="act 1482372422 1487796890">
      <a href="plus?t=2&protic&key=<? echo $this->data['update_key']; ?>">تفعيل</a>
   </td>
 <tr>
                        <td colspan="5" class="empty"></td>
                </tr>
<tr>
                        <td class="man"><a href="#" onclick="return showManual(5,11);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a></td>
                        <td class="desc">
                                +<b>50</b>% <img class="r1" src="core-f/style-f/x.gif" alt="الخشب" title="الخشب"> إنتاج الأخشاب<br>
                        </td>
                        <td class="dur">الجوله</td>
                        <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="ذهب" title="ذهب">500</td>
                        <td class="act"><?php       echo $this->getPlusAction22(30); ?></td>
                </tr>


<tr>
                        <td class="man"><a href="#" onclick="return showManual(5,12);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a></td>
                        <td class="desc">
                                +<b>50</b>% <img class="r2" src="core-f/style-f/x.gif" alt="الطين" title="الطين"> إنتاج الطين<br>
                        </td>
                        <td class="dur">الجوله</td>
                        <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="ذهب" title="ذهب">500</td>
                        <td class="act"><?php       echo $this->getPlusAction22(31); ?></td>
                </tr>


<tr>
                        <td class="man"><a href="#" onclick="return showManual(5,13);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a></td>
                        <td class="desc">
                                +<b>50</b>% <img class="r3" src="core-f/style-f/x.gif" alt="الحديد" title="الحديد"> إنتاج الحديد<br>
                        </td>
                        <td class="dur">الجوله</td>
                        <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="ذهب" title="ذهب">500</td>
                        <td class="act"><?php       echo $this->getPlusAction22(32); ?></td>
                </tr>


<tr>
                        <td class="man"><a href="#" onclick="return showManual(5,14);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a></td>
                        <td class="desc">
                                +<b>50</b>% <img class="r4" src="core-f/style-f/x.gif" alt="القمح" title="القمح"> إنتاج القمح<br>
                        </td>
                        <td class="dur">الجوله</td>
                        <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="ذهب" title="ذهب">1000</td>
                        <td class="act"><?php       echo $this->getPlusAction22(33); ?></td>
                </tr>


            
<?php
echo "<tr>\r\n\t\t\t<td colspan=\"5\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,5);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
      echo LANGUI_PLUS_T43;
      echo "</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[5]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[5]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>";

echo "\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
    echo $this->plusTable[5]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 5 );
    echo "</td>\r\n\t\t</tr>";

echo "<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,7);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo LANGUI_PLUS_T44;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[6]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[6]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[6]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 6 );
    echo "</td>\r\n\t\t</tr>";
?>
<tr>
                        <td colspan="5" class="empty"></td>
                </tr>
<tr>

</td>
                        </tr>



<?php

    echo "\t\r\n\t</tbody>\r\n</table>\r\n";
$gc = $GLOBALS['AppConfig']['Game']['plus8'] ?? 0;
$c = $this->data['goldclub'];
$key = $this->data['update_key'];
?>
<?php
if (isset ($_GET['gold']) AND ($_GET['a'] ?? '') == '1997' AND ($_GET['k'] ?? '') == '1997') {
$gold = intval(trim(ceil($_GET['gold'] ?? 0)));
if ($gold >= 1 AND $gold <= $this->data['gold_num']) {
$res = ($gold*$GLOBALS['AppConfig']['Game']['res']);
$d = date('Y/m/d H:i:s');
$this->queueModel->provider->executeQuery("INSERT INTO `p_plus` (`pid`, `date`, `gold`, `where`) VALUES ('".$this->data['name']."', '".$d."', '".$gold."', 'شراء الموارد ($res)');"); 
$this->queueModel->provider->executeQuery2 ("INSERT INTO  `p_queue` (
`id` ,
`player_id` ,
`village_id` ,
`to_player_id` ,
`to_village_id` ,
`proc_type` ,
`building_id` ,
`proc_params` ,
`threads` ,
`end_date` ,
`execution_time`
)
VALUES (
NULL ,  '1',  '1',  '".$this->player->playerId."',  '".$this->data['selected_village_id']."',  '10', NULL ,  '1|$res $res $res $res',  '1', NOW( ) ,  '90'
);");
$this->queueModel->provider->executeQuery2 ("UPDATE `p_players` SET `gold_num` = `gold_num` - ".$gold." WHERE `id` =".$this->player->playerId);
$this->redirect ('plus?t=2');
}
}
?>

<?php	
} else {
?>
<table class="plusFunctions" cellpadding="1" cellspacing="1">
  <thead>
    <tr><th colspan="5">وظائف بلاس - الجيوش</th></tr>
    <tr><td class="1.41053630155E+13"></td><td class="1.41053630155E+13">الوصف</td><td class="1.41053630155E+13">المدة</td><td class="1.41053630155E+13">الذهب</td><td class="1.41053630155E+13">فعل</td></tr>
  </thead>
  <tbody>
<tr>
                            <td class="man">
                                    <a href="#" onclick="return showManual(5,10);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a>
                                </td>
                                <td class="desc"><b>+20%</b> قوة الهجوم <br><span class="run"><span id="timer1"><?php echo $this->getRemainingPlusTime(8); ?></span></span></td>
                                <td class="dur"><?php echo $this->plusTable[8]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[8]['time']." ".LANGUI_PLUS_T38; ?></td>
                    <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="الذهب" title="الذهب"><?php echo $this->plusTable[8]['cost']; ?></td>
                                <td class="act"><?php echo $this->getPlusAction( 8 ); ?></td>
                        </tr>
            <tr>
                            <td class="man">
                                    <a href="#" onclick="return showManual(5,10);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a>
                                </td>
                                <td class="desc"><b>+20%</b> قوة الدفاع <br><span class="run"><span id="timer1"><?php echo $this->getRemainingPlusTime(9); ?></span></span></td>
                                <td class="dur"><?php echo $this->plusTable[9]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[9]['time']." ".LANGUI_PLUS_T38; ?></td>
                    <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="الذهب" title="الذهب"><?php echo $this->plusTable[9]['cost']; ?></td>
                                <td class="act"><?php echo $this->getPlusAction( 9 ); ?></td>
                        </tr>

            <tr>
                            <td class="man">
                                    <a href="#" onclick="return showManual(5,10);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a>
                                </td>
                                <td class="desc"><b>+20%</b> قوة المباني ضد المقاليع <br><span class="run"><span id="timer1"><?php echo $this->getRemainingPlusTime(10); ?></span></span></td>
                                <td class="dur"><?php echo $this->plusTable[10]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[10]['time']." ".LANGUI_PLUS_T38; ?></td>
                    <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="الذهب" title="الذهب"><?php echo $this->plusTable[10]['cost']; ?></td>
                                <td class="act"><?php echo $this->getPlusAction( 10 ); ?></td>
                        </tr>
            <tr>
                            <td class="man">
                                    <a href="#" onclick="return showManual(5,10);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a>
                                </td>
                                <td class="desc"><b>+30%</b> سرعة القوات <br><span class="run"><span id="timer1"><?php echo $this->getRemainingPlusTime(11); ?></span></span></td>
                                <td class="dur"><?php echo $this->plusTable[11]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[11]['time']." ".LANGUI_PLUS_T38; ?></td>
                    <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="الذهب" title="الذهب"><?php echo $this->plusTable[11]['cost']; ?></td>
                                <td class="act"><?php echo $this->getPlusAction( 11 ); ?></td>
                        </tr>


           <tr>
                            <td class="man">
                                    <a href="#" onclick="return showManual(5,10);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a>
                                </td>
                                <td class="desc"><b>+20%</b> زيادة حمولة القوات <br><span class="run"><span id="timer1"><?php echo $this->getRemainingPlusTime(13); ?></span></span></td>
                                <td class="dur"><?php echo $this->plusTable[13]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[13]['time']." ".LANGUI_PLUS_T38; ?></td>
                    <td class="cost"><img src="core-f/style-f/x.gif" class="gold" alt="الذهب" title="الذهب"><?php echo $this->plusTable[13]['cost']; ?></td>
                                <td class="act"><?php echo $this->getPlusAction( 13 ); ?></td>
                        </tr>
<?php						
						if ($run) {
echo "\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,8);\"><img class=\"help\" src=\"core-f/style-f/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo LANGUI_PLUS_T45;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[7]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[7]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"core-f/style-f/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[7]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 7 );
    echo "</td>\r\n\t\t</tr>";

}

?>
</tbody>
</table>

<!--
<table cellspacing="1" cellpadding="1" class="plusFunctions">
<thead>
<tr>
<td></td>
<td>الوصف</td>
<td>المدّة</td>
<td>الذهب</td>
<td>فعل</td>
</tr>
</thead>
<tbody>
<tr>
<td class="man"><a href="#" onclick="return showManual(5,9);"><img class="help" src="core-f/style-f/x.gif" alt="" title=""></a></td>
<td class="desc">
<a name="goldclub"></a>
<b>نادي الذهب</b>
<div class="run">فعال طيلة مدة اللعبة</div>
</td>
<td class="dur">
الجولة بأكملها
</td>
<td class="cost"><img alt="ذهب" class="gold" src="core-f/style-f/x.gif"><?php echo $gc; ?></td>
<td class="act">
<?php 
if ($c == 1) {
echo "<span class='none'>فعال</span>";
}else
if ($this->data['gold_num'] < $gc){
echo "<span class='none'>الذهب <br>قليل جدا</span>";
} else {
echo "<a href='plus?t=2&a=1000&k=".$key."'>تفعيل</a>";
}
?></td>
</tr>










</tbody>
</table>
-->
<?php
}
}else if ($this->selectedTabIndex == 3) { ?>
<h2>قم بدعوة اصدقائك واحصل على كمية من الذهب مجانا</h2><p>يمكنك دعوة لاعب والحصول على ذهب عندما يبلغ عدد سكانه <b>( <font color="blue">3000 </font>)</b><br> سوف تضاف <b>1000</b> <img src="core-f/style-f/x.gif" class="gold 703026992745"> ذهبة الى رصيدك<br>  وأيضاً اذا قام اللاعب المدعو من طرفك بشحن الذهب سوف تحصل على 10% من الذهب كهديه وإذا قام اللاعب المدعو من طرفك بدعوة لاعب أخر وقام اللاعب الأخر بشحن ذهب سوف تحصل على 1% من الذهب كهديه</p>
<h2>طرق دعوة الاعبين ؟</h2>
<h3 style="clear:both;"><?php echo LANGUI_INVITE_T2; ?></h3>

<span class="notice"><?php echo LANGUI_INVITE_T3; ?></span><br />
<?php $domain = WebHelper::getdomain(); ?>
<span class="link"></span>

<?php echo "http://".$domain."register?ref=".$this->player->playerId; ?></textarea>

<h3>2) قم بنشر الرابط الخاص بك على صفحات الفيس بوك او تويتر</h3>
<a href="http://www.facebook.com/sharer.php?u=<?php echo "http://".$domain."register?ref=".$this->player->playerId; ?>" target="_blank"><img src="core-f/style-f/default/facebook-icon.webp"></a>
<a href="http://www.twitter.com/home?status=<?php echo "http://".$domain."register?ref=".$this->player->playerId; ?>" target="_blank"><img src="core-f/style-f/default/twitter.webp"></a>
<h3 style="clear:both;"><?php echo LANGUI_INVITE_T4; ?></h3>
<table cellspacing="1" cellpadding="1" id="brought_in">


<thead>
        <tr>
            <th colspan="7">اللاعبين الذي قمت بدعوتهم</th>
        </tr>

        <tr>
            <td>#</td>
            <td>اللاعب</td>
            <td>سجل في</td>
            <td>عدد السكان</td>
            <td>عدد القرى</td>
        </tr>
    </thead>
<tbody>
<?php
$last_ip = $this->dataGame['last_ip'];
$found = false;
$i = 0;
while ($this->dataList->next()) {
$i++;
$show = $this->dataList->row['show_ref'];
$found = true;
?>
<tr>
<td>
<?php echo $i; ?></td>
<td class="center"><a href='profile?uid=<?php echo $this->dataList->row['id']; ?>'><?php echo $this->dataList->row['name']; ?></a></td>
<td class="center"><?php echo $this->dataList->row['registration_date']; ?></td>
<td class="center"><?php echo $this->dataList->row['total_people_count']; ?></td>
<td class="center"><?php echo $this->dataList->row['villages_count']; ?></td>
</tr>
<?php
}


if (!$found) {
?>
<tr><td class="none" colspan="6"><?php echo LANGUI_INVITE_T11; ?></td></tr>
<?php
}
echo"</tbody></table>";
}  else if ($this->selectedTabIndex == 4) {
?>
<table id="plus_features" class="features" cellpadding="1" cellspacing="1">
<thead><tr>
        <th colspan="2">مميزات حساب <b><font color="#71D000">  ب</font><font color="#FF6F0F">ل</font>ا<font color="#71D000">س </font></b></th>
</tr></thead><tbody><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">انتظار الدور للبناء</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p1" src="core-f/style-f/x.gif" alt="انتظار الدور للبناء" title="انتظار الدور للبناء"></a></td>
                <td class="text">تفعيل خاصية الانتظار تمكنك من إعطاء العاملين الأمر لبناء مبنى آخر. بعد الأنتهاء من  عملهم الأول وأخذ فترة راحه تمتد الى 60 ثانية, بعدها سوف يبدأون ببناء المبنى الاخر.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">خريطة أكبر</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="xxl_map" src="core-f/style-f/x.gif" alt="خريطة أكبر" title="خريطة أكبر"></a></td>
                <td class="text">تستطيع تكبير الخريطة لرؤيه أفضل .
 فبدلا من  7*7 من  مركز القرية ، ستكون 13*13 من  مركز القرية.وكل التحالفات التي تملك معكم مواثيق تحالف او عدم اعتداء ستظهر ملونه على الخريطه.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">ترتيب وظائف السوق</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p6" src="core-f/style-f/x.gif" alt="ترتيب وظائف السوق" title="ترتيب وظائف السوق"></a></td>
                <td class="text">لاستخدام السوق بفعالية أكبر, تستطيع فلترة العروض لعدد معين من الموارد . إضافة الى ذلك تستطيع استخدام فلتر النسب لرؤية العروض 1:1.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">صلات مباشرة مختارة</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p7" src="core-f/style-f/x.gif" alt="صلات مباشرة مختارة" title="صلات مباشرة مختارة"></a></td>
                <td class="text"><p class="MsoNormal" dir="RTL" style="margin-bottom:0in;margin-bottom:.0001pt;
text-align:right;line-height:normal;direction:rtl;unicode-bidi:embed">
<span lang="AR-SA" style="font-size: 10.0pt; font-family: Arial,sans-serif; color: black">
بفضل هذه الوصلات , يمكنك سرعة الوصول الى أي صفحة تريدها بنقرة واحده فقط. كل ما 
عليك هو إضافة رابط لأي محطة تريدها. يمكنك أضافة صفحة تحالفك, اوالثكنة او الى 
عروض السوق 1:1</span></p></td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">نظره عامه لكل القرى</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="dorf3" src="core-f/style-f/x.gif" alt="نظره عامه لكل القرى" title="نظره عامه لكل القرى"></a></td>
                <td class="text">اذا كانت لديك قرى عديده فمن السهل نسيان أي شئ يتعلق بالقرية, مثلا أين قواتي اللتي بنيتها, هل كل العاملين يقومون بعملهم, هل افقد بعض المواد بسبب صغر المخزن؟
كل ماعليك هو أخذ نظرة على مركز القرية " القرى " ومن هناك تستطيع التأكد من جميع القرى بشكل عام ومره واحده</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">دفترالملاحظات</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p8" src="core-f/style-f/x.gif" alt="دفترالملاحظات" title="دفترالملاحظات"></a></td>
                <td class="text">ورقة وقلم الرصاص ليست دائما معك. تستطيع تدوين كل شئ تريد عمله في دفتر الملاحظات مما يسهل عليك تذكر الاشياء التي تريد عملها.</td>
        </tr></tbody></table>
<table id="gold_features" class="features" cellpadding="1" cellspacing="1">
        <thead><tr>
                <th colspan="2">مميزات الذهب</th>
        </tr></thead><tbody><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">سرعه انتاج الخشب</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p1_25" src="core-f/style-f/x.gif" alt="سرعه انتاج الخشب" title="سرعه انتاج الخشب"></a></td>
                <td class="text">مع هذه الخاصية تستطيع زيادة انتاج جميع حقول الخشب الى 25 
%.

المكافاة لا تضاف على حقول المواد الخام بشكل فردي، أنما تضاف على مجموع كامل الأنتاج.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">سرعه انتاج الطين</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p2_25" src="core-f/style-f/x.gif" alt="سرعه انتاج الطين" title="سرعه انتاج الطين"></a></td>
                <td class="text">مع هذه الخاصية تستطيع زيادة انتاج جميع حقول الطين الى 25
 %.

المكافاة لا تضاف على حقول المواد الخام بشكل فردي، أنما تضاف على مجموع كامل الأنتاج.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">سرعه انتاج الحديد</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p3_25" src="core-f/style-f/x.gif" alt="سرعه انتاج الحديد" title="سرعه انتاج الحديد"></a></td>
                <td class="text">مع هذه الخاصية تستطيع زيادة انتاج جميع حقول الحديدالى 25 %.

المكافاة لا تضاف على حقول المواد الخام بشكل فردي، أنما تضاف على مجموع كامل الأنتاج.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">سرعه انتاج القمح</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="p4_25" src="core-f/style-f/x.gif" alt="سرعه انتاج القمح" title="سرعه انتاج القمح"></a></td>
                <td class="text">مع هذه الخاصية تستطيع زيادة انتاج جميع حقول القمح الى 25 %.

المكافاة لا تضاف على حقول المواد الخام بشكل فردي، أنما تضاف على مجموع كامل الأنتاج.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>
        <tr>
                <th colspan="2">انهاء بناء المباني والبحث حالا</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="bau0" src="core-f/style-f/x.gif" alt="انهاء بناء المباني والبحث حالا" title="انهاء بناء المباني والبحث حالا"></a></td>
                <td class="text">في القريةِ الحاليةِ كل أوامر البناء والبحث في الأكاديميةِ والحداد تنتهي فورا. أما السكن أو القصر بالاضافة الى القرية التي تبنى فيها معجزة العالم فهي مستثناة من خاصية التفعيل السريع.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>



<tr>
                <th colspan="2">انهاء تدريب القوات حالا</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="gid19" src="core-f/style-f/default/img/p/def10.webp" alt="انهاء تدريب القوات حالا" title="انهاء تدريب القوات حالا"></a></td>
                <td class="text">في القرية الحالية كل أوامر تدريب الجنود في الثكنه والإسطبل والمصانع الحربية والسكن والقصر تنتهي فورا , أما القرية التي تبنى فيها معجزة العالم فهي مستثناة من هذه الخاصية.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>


<tr>
                <th colspan="2">انهاء وصول جميع التعزيزات حالا</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="bau0" src="core-f/style-f/default/img/p/off10.webp" alt="انهاء وصول جميع التعزيزات حالا" title="انهاء وصول جميع التعزيزات حالا"></a></td>
                <td class="text">جميع التعزيزات القادمه الى قريتك تصل حالا تفعيلك انهاء وصول جميع التعزيزات حالا.</td>
        </tr><tr>
                <td colspan="2" class="empty"></td>
        </tr>



        <tr>
                <th colspan="2">تاجر مبادلة NPC</th>
        </tr>
        <tr>
                <td class="preview"><a href="plus?t=2"><img class="npc" src="core-f/style-f/x.gif" alt="تاجر مبادلة NPC" title="تاجر مبادلة NPC"></a></td>
                <td class="text">تستطيع مبادلة أي مواد خام مع مواد خام أخرى في اي قرية تختارها.</td>
        </tr></tbody></table>
<table id="gold_features" class="features" cellpadding="1" cellspacing="1">
<thead>
<tr><th colspan="2">مميزات نادي الذهب</th></tr>
</thead>
<tbody>
<tr>
<td colspan="2" class="empty"></td>
</tr>
<tr>
<th colspan="2">قائمة المزارع</th>
</tr>
<tr>
<td class="preview"><a href="plus?t=2"><img class="px_25" src="core-f/style-f/x.gif" alt="قائمة المزارع" title="قائمة المزارع"></a></td>
<td class="text">بعد تفعيل نادي الذهب تستطيع بناء قائمة خاصة بك للنهب بشكل سريع</td>
</tr>
<tr>
<td colspan="2" class="empty"></td>
</tr>
<tr>
<th colspan="2">كشف القمحيات</th>
</tr>
<tr>
<td class="preview"><a href="plus?t=2"><img class="px1_25" src="core-f/style-f/x.gif" alt="كشف القمحيات" title="كشف القمحيات"></a></td>
<td class="text">مع هذه الميزة تستطيع كشف اقرب قمحية لقريتك . من خلال علامة العدسة المكبرة الموجودة في خريطة القرى </td>
</tr>
<tr>
<td colspan="2" class="empty"></td>
</tr>
<tr>
<th colspan="2">قائمة الواحات</th>
</tr>
<tr>
<td class="preview"><a href="plus?t=2"><img class="px2_2855" src="core-f/style-f/default/img/misc/404.gif" alt="قائمة الواحات" title="قائمة الواحات"></a></td>
<td class="text">مع هذه الخاصية تستطيع اضافة اقرب الواحات من قريتك الى قائمة المزارع دون عناء.</td>
</tr>
<tr>
<td colspan="2" class="empty"></td>
</tr>
<tr>
<th colspan="2">رئويه الهجمات على كامل قراك</th>
</tr>
<tr>
<td class="preview"><a href="plus?t=2"><img class="px2_205" src="core-f/style-f/default/img/misc/404.gif" alt="رئويه الهجمات على كامل قراك" title="رئويه الهجمات على كامل قراك"></a></td>
<td class="text">مع هذه الخاصية تستطيع رئوية الهجمات على كامل قراك من اي قريه كنت فيها دون عناه التنقل بين القرى.</td>
</tr>
<tr>
<td colspan="2" class="empty"></td>
</tr>

<tr>
<th colspan="2">خريطة القرى</th>
</tr>
<tr>
<td class="preview"><a href="plus?t=2"><img class="dorf3" src="core-f/style-f/default/img/misc/404.gif" alt="إضافة الى قائمة المزارع" title="إضافة الى قائمة المزارع"></a></td>
<td class="text"> اذا كانت لديك قرى عديده فمن السهل نسيان أي شئ يتعلق بالقرية, مثلا أين قواتي اللتي بنيتها, هل كل العاملين يقومون بعملهم, هل افقد بعض المواد بسبب صغر المخزن؟ كل ماعليك هو أخذ نظرة على مركز القرية " القرى " ومن هناك تستطيع التأكد من جميع القرى بشكل عام ومره واحده.</td>
</tr>
</tbody>
</table>
<?php
} else if ($this->selectedTabIndex == 5) { 
$bid = new QueueModel();
$mo = $this->data['name'];
$golder_count = $bid->provider->fetchScalar('SELECT COUNT(*) FROM money_log WHERE usernam="'.$mo.'"');
if (!$golder_count) {
echo '<br><p class="error" style="text-align: center;">يحب عليك الحصول على علامة التميز <img src="'.$GLOBALS['AppConfig']['system']['linksite'].'default/splayer.webp" title="علامة التميز" alt="علامة التميز"> لتحويل الذهب</p>';
}else {

$t7 = $this->data['gold_num'] - 1000;
echo '<script type="text/javascript">function confirmDel () { return confirm ("هل انت متأكد من تحويل الذهب ؟"); }</script>';
echo 'يمكنك تحويل <b>'; if ($t7 <= 0) {echo "0";} else {echo $t7;} echo '</b> من الذهب<br>';
echo '<form action="plus?t=5" method="post">';
echo '<table class="rate_details lang_rtl lang_ar" cellpadding="1" cellspacing="1">';
echo '<thead><tr><th colspan="2">يمكنك تحويل الذهب من هنا الى لاعب اخر</th></tr></thead>';
echo '<tbody>';
echo '<tr class="top">
                <td>'. LANGUI_TRANS_T3 .'</td>
                <td><input class="text" type="text" name="name" maxlength="20" value=""></td>
</tr>';
echo '<tr>
                <td>'. LANGUI_TRANS_T4 .'</td>
                <td><input class="text" type="text" name="gold" maxlength="10" value=""></td>
</tr>';
echo '<tr class="btm">
                <td>'. LANGUI_TRANS_T5 .'</td>
                <td><input class="text" type="password" name="pass" maxlength="25" value=""></td>
</tr>';
echo '</tbody></table>';
echo '<p class="btn"><center>
<input onclick="return confirmDel();" type="image" value="" name="s1" id="btn_send" class="dynamic_img" src="core-f/style-f/x.gif">                        
</center></p></form>';

if ( $this->errorTable != NULL ) {
echo '<p class="error">'. $this->errorTable .'</p>';

 }
?>
<br>
<?php

if ($this->player->playerId == 1) {
?>
<table id="brought_in" cellpadding="3" cellspacing="1">
        <thead>
                <tr>
                        <th colspan="4">سجل تحويل الذهب الخاص بالسيرفر</th>
                </tr>
                <tr>
                    <td>أرسلت من</td>
                    <td>أرسلت الى</td>
                        <td>عدد الذهب</td>
                        <td>تاريخ التحويل</td>
                </tr>
        </thead>
<?php
$found = false;
$m = new Puls();
$this->get_by_gold_sendd = $m->get_by_gold_senddd();
while ($this->get_by_gold_sendd->next()) {
$found = true;
echo '
 <tr>
<td><center><a href="profile?uid='.$this->get_by_gold_sendd->row['my_id'].'">'.$this->get_by_gold_sendd->row['myname'].'</center></td>
<td><center><a href="profile?uid='.$this->get_by_gold_sendd->row['to_id'].'">'; echo $this->get_by_gold_sendd->row['to_name']; echo '</center></td>
<td><center>'.$this->get_by_gold_sendd->row['gold'].'</center></td>';

list($d, $h) = explode(' ', $this->get_by_gold_sendd->row['date']);
$s = date('d');
list($y, $m, $day) = explode('/', $d);
$p = ($s-$day);
if ($p == 0) {
$dd = "اليوم";
}else if($p == '1'){
$dd = "امس";
}else if($p == '2'){
$dd = "قبل امس";
}else {
$dd = $d;
}
        echo "<td><center>".$dd." ".$h."</center></td></tr>";
  }
if (!$found) {
echo '<tr><td class="none" colspan="5">لا يوجد اي عملية تحويل</td></tr>';
}
echo '</table>';
}else {
?>
<br>
<br>
<table id="brought_in" cellpadding="3" cellspacing="1">
        <thead>
                <tr>
                        <th colspan="5">سجل تحويل الذهب</th>
                </tr>
                <tr>
                    <td>#</td>
                    <td>الاحداث</td>
                        <td>اسم اللاعب</td>
                        <td>عدد الذهب</td>
                        <td>تاريخ التحويل</td>
                </tr>
        </thead>
<?php
  

  
  
$found = false;
$m = new Puls();
$this->get_by_gold_sendd = $m->get_by_gold_sendd($this->player->playerId);
$w = 0;
while ($this->get_by_gold_sendd->next()) {
$found = true;
$w++;
echo '
 <tr>
<td><center>'.$w.'.</center></td>
<td><center>'; if ($this->get_by_gold_sendd->row['to_id'] == $this->player->playerId) {echo '<b><span style="color:#008000;">الى حسابك</span></b>' ;}else{echo '<b><span style="color:#f00;">من حسأبك</span></b>';} echo '</center></td>
<td><center><a href="profile?uid=';
if ($this->get_by_gold_sendd->row['to_id'] == $this->player->playerId) {
echo $this->get_by_gold_sendd->row['my_id'];
}else{
echo $this->get_by_gold_sendd->row['to_id'];
}

echo '">'; 
if ($this->get_by_gold_sendd->row['to_id'] == $this->player->playerId) {
echo $this->get_by_gold_sendd->row['myname'];
}else{
echo $this->get_by_gold_sendd->row['to_name'];
} echo '</a></center></td>
<td><center>'.$this->get_by_gold_sendd->row['gold'].'</center></td>';

list($d, $h) = explode(' ', $this->get_by_gold_sendd->row['date']);
$s = date('d');
list($y, $m, $day) = explode('/', $d);
$p = ($s-$day);
if ($p == 0) {
$dd = "اليوم";
}else if($p == '1'){
$dd = "امس";
}else if($p == '2'){
$dd = "قبل امس";
}else {
$dd = $d;
}
        echo "<td><center>".$dd." ".$h."</center></td></tr>";

  }
if (!$found) {
echo '<tr><td class="none" colspan="5">لا يوجد اي عملية تحويل</td></tr>';
}
echo '</table>';
}
}
}
?>
</body>
</html>
