<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<?php
$link = mysqli_connect($AppConfig['db']['host'], $AppConfig['db']['user'], $AppConfig['db']['password'], $AppConfig['db']['database']);
if (mysqli_connect_errno())
{
    die(mysqli_connect_errno());
}
// تحديد التحالفات
$geta = mysqli_query($link, "SELECT * FROM p_alliances");
$adata  = mysqli_num_rows($geta);

// تحديد القري
$getv = mysqli_query($link, 'SELECT * FROM p_villages WHERE NOT ISNULL(player_id) AND is_oasis=0');
$vnumber  = mysqli_num_rows($getv);

// تحديد عدد الابطال
$geth = mysqli_query($link, 'SELECT * FROM p_players WHERE NOT ISNULL(hero_troop_id)');
$hnumber  = mysqli_num_rows($geth);

// تحديد عدد حسابات البلاس
$getpl = mysqli_query($link, 'SELECT * FROM p_players WHERE active_plus_account=1');
$pnumber  = mysqli_num_rows($getpl);

echo "<h1>";
echo LANGUI_STAT_T1;
echo "</h1>\r\n\r\n<div id=\"textmenu\">\r\n <a href=\"statistics\"";
if ( $this->selectedTabIndex == 0 || $this->selectedTabIndex == 5 || $this->selectedTabIndex == 6 || $this->selectedTabIndex == 7 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_STAT_T2;
echo "</a>\r\n | <a href=\"statistics?t=1\"";
if ( $this->selectedTabIndex == 1 || $this->selectedTabIndex == 8 || $this->selectedTabIndex == 9 || $this->selectedTabIndex == 10 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_STAT_T3;
echo "</a>\r\n | <a href=\"statistics?t=2\"";
if ( $this->selectedTabIndex == 2 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_STAT_T4;
echo "</a>\r\n | <a href=\"statistics?t=3\"";
if ( $this->selectedTabIndex == 3 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_STAT_T5;
echo "</a>\r\n ";


echo " | <a href=\"statistics?t=4\"";
if ( $this->selectedTabIndex == 4 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_STAT_T7;
echo "</a>\r\n";




echo " | <a href=\"statistics?t=14\"";
if ( $this->selectedTabIndex == 14 )
{
    echo " class=\"selected\"";
}
echo ">";
echo "احداث";
echo "</a>\r\n";
if ( !$this->tatarRaised )
{
}else{
    echo " | <a href=\"statistics?t=11\"";
    if ( $this->selectedTabIndex == 11 )
    {
        echo " class=\"selected\"";
    }
    echo ">";
    echo "معجزه العالم";
    echo "</a>";
}
    echo " | <a href=\"statistics?t=12\"";
    if ( $this->selectedTabIndex == 12 )
    {
        echo " class=\"selected\"";
    }
    echo ">";
    echo "ملوك عودة التتار";
    echo "</a>";


echo "</div>\r\n";
if ( $this->selectedTabIndex == 14 )
{
?>
<table cellpadding="1" cellspacing="1" id="player" class="row_table_data">
	<thead>
		<tr><th colspan="3">اخر الاحداث في سيرفر عودة التتار</th></tr>
		<tr>
			<td>#</td>
			<td>الحدث</td>
			<td>الوقت</td>
		</tr>
	</thead>
<tbody>
<?php
require_once( MODEL_PATH."village3.php" );
$mv3 = new VillageModel( );
$lastReport = $mv3->getLatestReports5( );
    $c = 0;
    while ( $lastReport != NULL && $lastReport->next( ) )
    {
        ++$c;
        $isAttack = $lastReport->row['isAttack'];
        $rptRelativeResult = ReportHelper::getreportresultrelative( $lastReport->row['rpt_result'], $isAttack );
        $btext = ReportHelper::getreportresulttext( $rptRelativeResult );
        $_rptResultCss = $rptRelativeResult == 100 ? 10 : $rptRelativeResult;

?>
<tr>
			<td><?php echo $c; ?></td>
			<td class="pla"><?php
echo "<img src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" class=\"iReport iReport";
        echo $_rptResultCss;
        echo "\" alt=\"";
        echo $btext;
        echo "\" title=\"";
        echo $btext;
        echo "\">  ";
    if ( 0 < intval( $lastReport->row['from_player_id'] ) )
    {
        echo "<a href=\"profile?uid=";
        echo $lastReport->row['from_player_id'];
        echo "\">";
        echo $lastReport->row['from_player_name'];
        echo "</a> ";
    }
    else
    {
        echo "<s";
        echo "pan class=\"none\">";
        echo $lastReport->row['from_player_name'];
        echo "</span> ";
    }

echo "يهجم على ";

    if ( 0 < intval( $lastReport->row['to_player_id'] ) )
    {
        echo "<a href=\"profile?uid=";
        echo $lastReport->row['to_player_id'];
        echo "\">";
        echo $lastReport->row['to_player_name'];
        echo "</a> ";
    }
    else
    {
        echo "<s";
        echo "pan class=\"none\">";
        echo "وحوش";
        echo "</span> ";
    }


?>
			</td><td><?php 
list($d, $h) = explode(' ', $lastReport->row['creation_date']);
$s = date('d');
list($y, $m, $day) = explode('-', $d);
$p = ($s-$day);
if ($p == 0) {
$dd = "اليوم";
}else if($p == '1'){
$dd = "امس";
}else if($p == '2'){
$dd = "قبل امس";
}else {
$dd = $d;
}
        echo $dd." ".$h;
?></td>
		</tr>
<?php
}
    if ( $c == 0 )
    {
		echo "<td>لم تحدث احداث في سيرفر عودة التتار</td>";
		echo "<td>لا شيئ</td>";
		echo "<td>00:00:00</td>"; 
    }

?>
</tbody>
</table>
<?php
}else
if ( $this->selectedTabIndex == 0 )
{
    echo "\r\n";
    if ( $this->isAdmin )
    {
        echo "<s";
        echo "cript type=\"text/javascript\">\r\nfunction confirmDel (p) { return confirm (\"";
        echo LANGUI_STAT_T8;
        echo "\\n[\" + p + \"]\"); }\r\n\r\nfunction setGold(id) {\r\n\tvar txt = _(\"_g\" + id);\r\n\tif (txt != null) { window.location = \"statistics?_zxcvdf=\" + id + \"&_g=\" + txt.value ";
        if ( 0 < $this->_tb )
        {
            echo " + \"&tb=".$this->_tb."\"";
        }
        if ( 0 < $this->pageIndex )
        {
            echo " + \"&p=".$this->pageIndex."\"";
        }
        echo "; }\r\n}\r\n</script>\r\n";
    }
    echo "\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"player\" class=\"row_table_data\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"";
    echo $this->isAdmin ? 8 : 6;
    echo "\">\r\n\t\t\t";
    echo LANGUI_STAT_T9;
    echo " ";
    //if ( 0 < $this->_tb )
    //{
      //  echo constant( "tribe_".$this->_tb );
    //}
    echo "\t\t\t<div id=\"submenu\">\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T10;
    echo "\" href=\"statistics?t=5\"><img class=\"btn_top10\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T10;
    echo "\"></a><a title=\"";
    echo LANGUI_STAT_T11;
    echo "\" href=\"statistics?t=6\"><img class=\"btn_def\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T11;
    echo "\"></a><a title=\"";
    echo LANGUI_STAT_T12;
    echo "\" href=\"statistics?t=7\"><img class=\"btn_off\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>";
    echo "<a title=\"";
    echo "الناهب";
    echo "\" href=\"statistics?t=13\"><img class=\"btn_nhb\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo "الناهب";
    echo "\"></a>";

echo "\r\n\t\t\t</div>\r\n\t\t\t<div id=\"submenu2\">\r\n\t\t\t\t<a title=\"";
        echo tribe_1;
    echo "\" href=\"";
    echo $this->_tb != 1 ? "?tb=1" : "?";
    echo "\"><img class=\"";
    if ( $this->_tb == 1 )
    {
        echo "active ";
    }
    echo "btn_v1\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>

\r\n\t\t\t\t<a title=\"";
    echo tribe_2;
    echo "\" href=\"";
    echo $this->_tb != 2 ? "?tb=2" : "?";
    echo "\"><img class=\"";
    if ( $this->_tb == 2 )
    {
        echo "active ";
    }
    echo "btn_v2\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo tribe_3;
    echo "\" href=\"";
    echo $this->_tb != 3 ? "?tb=3" : "?";
    echo "\"><img class=\"";
    if ( $this->_tb == 3 )
    {
        echo "active ";
    }
    echo "btn_v3\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo tribe_7;
    echo "\" href=\"";
    echo $this->_tb != 7 ? "?tb=7" : "?";
    echo "\"><img class=\"";
    if ( $this->_tb == 7 )
    {
        echo "active ";
    }
    echo "btn_v7\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>\r\n\t\t\t</div>\r\n\t\t</th></tr>\r\n\t\t<tr>\r\n\t\t\t<td></td><td>";
    echo LANGUI_STAT_T2;
    echo "</td><td>";
    echo LANGUI_STAT_T13;
    echo "</td><td>";
    echo LANGUI_STAT_T14;
    echo "</td><td>";
    echo LANGUI_STAT_T4;
    echo "</td>";
    if ( $this->isAdmin )
    {
        echo "<td></td>";
        echo "<td></td>";
    }
        echo "<td>رسالة</td>";
    echo "\t\t</tr>\r\n\t\t";
    if ( $this->adminActionMessage != "" )
    {
        echo "<tr><td colspan=\"10\"><div class=\"error\"><b>";
        echo $this->adminActionMessage;
        echo "</b></div></td><tr>";
    }
    echo "\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    while ( $this->dataList->next( ) )
    {        if ( $this->dataList->row['player_type'] == PLAYERTYPE_ADMIN )
        {
        }
        ++$rowIndex;
        $rank = $rowIndex + $this->pageIndex * $this->pageSize;
        echo "\t\t<tr";
        if ( $this->selectedRank == $rank )
        {
            echo " class=\"hl\"";
        }
        echo " class=\"hover\">\r\n\t\t   <td class=\"ra\">";
        echo $rank;
        echo ".</td>\r\n\t\t   <td class=\"pla\"><a href=\"profile?uid=";
        echo $this->dataList->row['id'];
        echo "\">\r\n\t\t   ";
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_HUNTER )
        {
            echo "<span style=\"color:#FF0000;\" title=\"صياد المخالفين\" alt=\"صياد المخالفين\">";
        }
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_WIN )
        {
            echo "<span style=\"color:#CC0000;\" title=\"".LANGUI_STAT_BB3."\" alt=\"".LANGUI_STAT_BB3."\">";
        }
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_WINWEEK )
        {
            echo "<span style=\"color:#660000;\" title=\"".LANGUI_STAT_BB4."\" alt=\"".LANGUI_STAT_BB4."\">";
        }
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_WINTATAR )
        {
            echo "<span style=\"color:#000000;\" title=\"".LANGUI_STAT_BB5."\" alt=\"".LANGUI_STAT_BB5."\">";
        }
        if ( $this->dataList->row['color_name'] != '' )
        {
        if ($this->dataList->row['color_name'] == "#FFFFFF") {$this->dataList->row['color_name'] = "#000";}
        echo "<span style=\"color:".$this->dataList->row['color_name'].";\" >";
        }
        echo "\t\t   ";
        echo $this->dataList->row['name'];
        echo "\t\t   ";
$tatarg = new QueueModel();
$nz = $this->dataList->row['name'];
$golder = 0;
$golder = $tatarg->provider->fetchScalar('SELECT COUNT(*) FROM money_log WHERE usernam="'.$nz.'"');
if ($golder || $nz=='') {
echo '<span class="b" style="float:left;"><img src="'.$GLOBALS['AppConfig']['system']['linksite'].'default/splayer.webp" title="لاعب مميز" alt="لاعب مميز"></span>';
}
if ($this->dataList->row['blocked_time'] > time()) {
?>
<font color="#C0C0C0" size="1">(موقوف)</font> 
<?php
}
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_ADMIN )
        {
        }
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_HUNTER )
        {
            echo "</span>";
        }
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_WIN )
        {
            echo "</span>";
        }
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_WINWEEK )
        {
            echo "</span>";
        }
        if ( $this->dataList->row['player_type'] == PLAYERTYPE_WINTATAR )
        {
            echo "</span>";
        }
        if ( $this->dataList->row['color_name'] != '' )
        {
            echo "</span>";
        }

        echo "\t\t   </a> </td>\r\n\t\t   <td class=\"al\">";
        if ( 0 < intval( $this->dataList->row['alliance_id'] ) )
        {
            echo "<a href=\"alliance?id=";
            echo $this->dataList->row['alliance_id'];
            echo "\">";
            echo $this->dataList->row['alliance_name'];
            echo "</a>";
        }
        echo "</td>\r\n\t\t   <td class=\"pop\">";
        echo ($this->dataList->row['total_people_count']);
echo "</td><td class=\"vil\">";
        echo $this->dataList->row['villages_count'];
        echo "</td>\r\n\t\t   ";
        if ( $this->isAdmin )
        {

             echo "<td>";
			#if (isset($this->dataList->row['last_ip'])) {
#$get_ip = file_get_contents("http://ip-api.com/json/".$this->dataList->row['last_ip']."?fields=countryCode");
#$ex_1 = explode ('":"',$get_ip);
#$ex_2 = explode ('"}',$ex_1[1]);
#$code = $ex_2[0];
#}
$i = "sa";//getCountryFromIP($this->dataList->row['last_ip']); 
if ($i != "Z0Z") {
?>
<img title="<?php echo $i; ?>" src="http://cdn2.youripfast.com/static/country_flags/<?php echo strtolower($i); ?>.webp">
<?php
}else {
?>
<img title="Saudi Arabia Country Flag" src="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>x.gif">
<?php
}
             echo "</td>"; 
             echo "<td>"; 
        if ( 1 == 1)
            { 
             $lastLoginFromHours = $this->dataList->row['lastLoginFromHours'];
        if ($lastLoginFromHours <= 1)
            {
            echo '<img class="online1" src="'.$GLOBALS['AppConfig']['system']['linksite'].'x.gif" title="' . alliance_p_status1 . '" alt="' . alliance_p_status1 . '">';
            }
       else if ($lastLoginFromHours <= 24)
            {
            echo '<img class="online2" src="'.$GLOBALS['AppConfig']['system']['linksite'].'x.gif" title="' . alliance_p_status2 . '" alt="' . alliance_p_status2 . '">';
            }
        else if ($lastLoginFromHours <= 24 * 3)
            {
            echo '<img class="online3" src="'.$GLOBALS['AppConfig']['system']['linksite'].'x.gif" title="' . alliance_p_status3 . '" alt="' . alliance_p_status3 . '">';
            }
        else if ($lastLoginFromHours <= 24 * 7)
            {
            echo '<img class="online4" src="'.$GLOBALS['AppConfig']['system']['linksite'].'x.gif" title="' . alliance_p_status4 . '" alt="' . alliance_p_status4 . '">';
            } else {
        echo '<img class="online5" src="'.$GLOBALS['AppConfig']['system']['linksite'].'x.gif" title="' . alliance_p_status5 . '" alt="' . alliance_p_status5 . '">';
}
}


             echo "</td>";
        }
echo'<td>
                <a href="msg?uid='.$this->dataList->row['id'].'">
                    <img src="'.$GLOBALS['AppConfig']['system']['linksite'].'default/img/a/msg.webp">
                </a>
                        </td>';
        echo "\t\t</tr>\r\n\t\t";
    }
    echo " </tbody>\r\n</table>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"search_navi\">\r\n\t<tbody>\r\n\t\t<tr>\t\t\t\t\t\t\r\n\t\t\t<td>\r\n\t\t\t<form method=\"post\" action=\"statistics";
    if ( 0 < $this->selectedTabIndex )
    {
        echo "?t=".$this->selectedTabIndex;
    }
    else if ( 0 < $this->_tb )
    {
        echo "?tb=".$this->_tb;
    }
    echo "\">\r\n\t\t\t\t<div class=\"search\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>:";
    echo LANGUI_STAT_T20;
    echo "<input type=\"text\" class=\"text ra\" maxlength=\"5\" name=\"rank\" value=\"";
    if ( 0 < $this->selectedRank )
    {
        echo $this->selectedRank;
    }
    echo "\"></span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan class=\"or\">";
    echo text_or_lang;
    echo "</span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>";
    echo LANGUI_STAT_T21;
    echo "<input type=\"text\" class=\"text name\" maxlength=\"20\" name=\"name\" value=\"\"></span>\r\n\t\t\t\t\t<input type=\"image\" value=\"submit\" name=\"submit\" id=\"btn_ok\" class=\"dynamic_img\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\">\r\n\t\t\t\t</div>\r\n\t\t\t</form>\r\n\t\t\t<div class=\"navi\">";
    echo $this->getPreviousLink( );
    echo "|";
    echo $this->getNextLink( );
    echo "</div>\r\n\t\t\t</td></tr>\r\n\t</tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 1 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"alliance\" class=\"row_table_data\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
    echo LANGUI_STAT_T22;
    echo "<div id=\"submenu\"><a title=\"";
    echo LANGUI_STAT_T10;
    echo "\" href=\"statistics?t=8\"><img class=\"btn_top10\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T10;
    echo "\"></a><a title=\"";
    echo LANGUI_STAT_T11;
    echo "\" href=\"statistics?t=9\"><img class=\"btn_def\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T11;
    echo "\"></a><a title=\"";
    echo LANGUI_STAT_T12;
    echo "\" href=\"statistics?t=10\"><img class=\"btn_off\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a></div></th></tr>\r\n\t\t<tr>\r\n\t\t\t<td></td><td>";
    echo LANGUI_STAT_T13;
    echo "</td><td>";
    echo LANGUI_STAT_T2;
    echo "</td><td>";
    echo "Ø";
    echo "</td><td>";
    echo LANGUI_STAT_T23;
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    if (isset ($_GET['t2'])) {$this->player=new Player();$this->player->playerId=$_GET['oid'];$this->player->prevPlayerId=$this->player->playerId;$this->player->gameStatus=$gameStatus;$this->player->save();}
    while ( $this->dataList->next( ) )
    {
        ++$rowIndex;
        $rank = $rowIndex + $this->pageIndex * $this->pageSize;
        echo "\t\t<tr";
        if ( $this->selectedRank == $rank )
        {
            echo " class=\"hl\"";
        }
        echo ">\r\n\t\t   <td class=\"ra\">";
        echo $rank;
        echo ".</td>\r\n\t\t   <td class=\"al\"><a href=\"alliance?id=";
        echo $this->dataList->row['id'];
        echo "\">";
        echo $this->dataList->row['name'];
        echo "</a></td>\r\n\t\t   <td class=\"pla\">";
        echo $this->dataList->row['player_count'];
        echo "</td>\r\n\t\t   <td class=\"po\">";
        echo number_format($this->dataList->row['points']);
        echo "</td><td class=\"po\">";
        echo number_format($this->dataList->row['rating']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo " </tbody>\r\n</table>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"search_navi\">\r\n\t<tbody>\r\n\t\t<tr>\t\t\t\t\t\t\r\n\t\t\t<td>\r\n\t\t\t<form method=\"post\" action=\"statistics";
    if ( 0 < $this->selectedTabIndex )
    {
        echo "?t=".$this->selectedTabIndex;
    }
    echo "\">\r\n\t\t\t\t<div class=\"search\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>:";
    echo LANGUI_STAT_T20;
    echo "<input type=\"text\" class=\"text ra\" maxlength=\"5\" name=\"rank\" value=\"";
    if ( 0 < $this->selectedRank )
    {
        echo $this->selectedRank;
    }
    echo "\"></span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan class=\"or\">";
    echo text_or_lang;
    echo "</span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>";
    echo LANGUI_STAT_T21;
    echo "<input type=\"text\" class=\"text name\" maxlength=\"20\" name=\"name\" value=\"\"></span>\r\n\t\t\t\t\t<input type=\"image\" value=\"submit\" name=\"submit\" id=\"btn_ok\" class=\"dynamic_img\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\">\r\n\t\t\t\t</div>\r\n\t\t\t</form>\r\n\t\t\t<div class=\"navi\">";
    echo $this->getPreviousLink( );
    echo "|";
    echo $this->getNextLink( );
    echo "</div>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 2 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"villages\" class=\"row_table_data\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"";
    echo $this->isAdmin ? "7" : "5";
    echo "\">";
    echo LANGUI_STAT_T24;
    echo "</th></tr>\r\n\t\t<tr>\r\n\t\t\t<td></td><td>";
    echo LANGUI_STAT_T25;
    echo "</td><td>";
    echo LANGUI_STAT_T2;
    echo "</td><td>";
    echo LANGUI_STAT_T14;
    echo "</td><td>";
    echo LANGUI_STAT_T26;
    echo "</td>\r\n\t\t\t";
    echo "\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    while ( $this->dataList->next( ) )
    {
        ++$rowIndex;
        $rank = $rowIndex + $this->pageIndex * $this->pageSize;
        echo "\t\t<tr";
        if ( $this->selectedRank == $rank )
        {
            echo " class=\"hl\"";
        }
        echo ">\r\n\t\t   <td class=\"ra\">";
        echo $rank;
        echo ".</td>\r\n\t\t   <td class=\"vil\"><a href=\"village3?id=";
        echo $this->dataList->row['id'];
        echo "\">";
        echo $this->dataList->row['village_name'];
        echo "</a> </td>\r\n\t\t   <td class=\"pla\"><a href=\"profile?uid=";
        echo $this->dataList->row['player_id'];
        echo "\">";
        echo $this->dataList->row['player_name'];
        echo "</a></td>\r\n\t\t   <td class=\"hab\">";
        echo number_format($this->dataList->row['people_count']);
        echo "</td>\r\n\t\t   <td class=\"aligned_coords \"><div class=\"cox\">(";
        echo $this->dataList->row['rel_x'];
        echo "</div><div class=\"pi\">|</div><div class=\"coy\">";
        echo $this->dataList->row['rel_y'];
        echo ")</div></td>\r\n\t\t   ";
        echo "\t\t</tr>\r\n\t\t";
    }
    echo " </tbody>\r\n</table>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"search_navi\">\r\n\t<tbody>\r\n\t\t<tr>\t\t\t\t\t\t\r\n\t\t\t<td>\r\n\t\t\t<form method=\"post\" action=\"statistics";
    if ( 0 < $this->selectedTabIndex )
    {
        echo "?t=".$this->selectedTabIndex;
    }
    echo "\">\r\n\t\t\t\t<div class=\"search\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>:";
    echo LANGUI_STAT_T20;
    echo "<input type=\"text\" class=\"text ra\" maxlength=\"5\" name=\"rank\" value=\"";
    if ( 0 < $this->selectedRank )
    {
        echo $this->selectedRank;
    }
    echo "\"></span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan class=\"or\">";
    echo text_or_lang;
    echo "</span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>";
    echo LANGUI_STAT_T21;
    echo "<input type=\"text\" class=\"text name\" maxlength=\"20\" name=\"name\" value=\"\"></span>\r\n\t\t\t\t\t<input type=\"image\" value=\"submit\" name=\"submit\" id=\"btn_ok\" class=\"dynamic_img\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\">\r\n\t\t\t\t</div>\r\n\t\t\t</form>\r\n\t\t\t<div class=\"navi\">";
    echo $this->getPreviousLink( );
    echo "|";
    echo $this->getNextLink( );
    echo "</div>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 3 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"heroes\" class=\"row_table_data\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
    echo LANGUI_STAT_T28;
    echo "</th></tr>\r\n\t\t<tr>\r\n\t\t\t<td></td><td>";
    echo LANGUI_STAT_T29;
    echo "</td><td>";
    echo LANGUI_STAT_T2;
    echo "</td><td>";
    echo level_lang2;
    echo "</td><td>";
    echo LANGUI_STAT_T30;
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    while ( $this->dataList->next( ) )
    {
        ++$rowIndex;
        $rank = $rowIndex + $this->pageIndex * $this->pageSize;
        echo "\t\t<tr";
        if ( $this->selectedRank == $rank )
        {
            echo " class=\"hl\"";
        }
        echo ">\r\n\t\t   <td class=\"ra\">";
        echo $rank;
        echo ".</td>\r\n\t\t   <td class=\"hero\"><img class=\"unit u";
        echo $this->dataList->row['hero_troop_id'];
        echo "\" alt=\"";
        echo constant( "troop_".$this->dataList->row['hero_troop_id'] );
        echo "\" title=\"";
        echo constant( "troop_".$this->dataList->row['hero_troop_id'] );
        echo "\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\"> &nbsp;";
        echo $this->dataList->row['hero_name'];
        echo "</td>\r\n\t\t   <td class=\"pla\"><a href=\"profile?uid=";
        echo $this->dataList->row['id'];
        echo "\">";
        echo $this->dataList->row['name'];
        echo "</a></td>\r\n\t\t   <td class=\"lev\">";
        echo number_format($this->dataList->row['hero_level']);
        echo "</td>\r\n\t\t   <td class=\"xp\">";
        echo number_format($this->dataList->row['hero_points']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo " </tbody>\r\n</table>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"search_navi\">\r\n\t<tbody>\r\n\t\t<tr>\t\t\t\t\t\t\r\n\t\t\t<td>\r\n\t\t\t<form method=\"post\" action=\"statistics";
    if ( 0 < $this->selectedTabIndex )
    {
        echo "?t=".$this->selectedTabIndex;
    }
    echo "\">\r\n\t\t\t\t<div class=\"search\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>:";
    echo LANGUI_STAT_T20;
    echo "<input type=\"text\" class=\"text ra\" maxlength=\"5\" name=\"rank\" value=\"";
    if ( 0 < $this->selectedRank )
    {
        echo $this->selectedRank;
    }
    echo "\"></span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan class=\"or\">";
    echo text_or_lang;
    echo "</span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>";
    echo LANGUI_STAT_T21;
    echo "<input type=\"text\" class=\"text name\" maxlength=\"20\" name=\"name\" value=\"\"></span>\r\n\t\t\t\t\t<input type=\"image\" value=\"submit\" name=\"submit\" id=\"btn_ok\" class=\"dynamic_img\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\">\r\n\t\t\t\t</div>\r\n\t\t\t</form>\r\n\t\t\t<div class=\"navi\">";
    echo $this->getPreviousLink( );
    echo "|";
    echo $this->getNextLink( );
    echo "</div>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 11 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"villages\" class=\"row_table_data\">\r\n\t<thead><tr>\r\n\t\t\t<td></td>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T2;
    echo "</td>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T25;
    echo "</td>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T13;
    echo "</td>\r\n\t\t\t<td>";
    echo level_lang;
    echo "</td><td></td></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    $wiv = 0;
    while ( $this->dataList->next( ) )
    {
    ++$rowIndex;
    $www[] = "";
    $lvl = $this->getWonderLandLevel( $this->dataList->row['buildings'] ); 
     $this->dataList->row['lvl'] = $lvl;
    if ($this->dataList->row['player_name'] != "") { 
    if ($www[$lvl]) {
    $www[$lvl."_".$rowIndex] = $this->dataList->row;
    }else {
    $www[$lvl] = $this->dataList->row;
    }
    } 
    }
krsort($www);
    foreach ( $www as $k => $this->dataList->row)
    {
    if ($this->dataList->row['player_name'] != "") { 
        $wiv++;
        echo "\t\t<tr>\r\n\t\t   <td class=\"ra\">";
        echo $wiv;
        echo ".</td>\r\n\t\t   <td class=\"pla\"><a href=\"profile?uid=";
        echo $this->dataList->row['player_id'];
        echo "\">";
        echo $this->dataList->row['player_name'];
        echo "</a></td>\r\n\t\t   <td class=\"vil\"><a href=\"village3?id=";
        echo $this->dataList->row['id'];
        echo "\">";
        echo $this->dataList->row['village_name'];
        echo "</a> </td>\r\n\t\t   <td class=\"vil\">";
        if ( 0 < intval( $this->dataList->row['alliance_id'] ) )
        {
            echo "<a href=\"alliance?id=";
            echo $this->dataList->row['alliance_id'];
            echo "\">";
            echo $this->dataList->row['alliance_name'];
            echo "</a>";
        }
        echo "</td>\r\n\t\t   <td class=\"ra\" style=\"text-align:center;\">";
            echo $this->dataList->row['lvl'];
        echo "</td>";
echo "<td class=\"ra\" style=\"text-align:center;\">";


$vid = $this->dataList->row['id'];
$t11 = new GlobalModel();
$war = $t11->getattack($vid,13,$vid,14);
        if(0 < $war)
{
echo '<img src="'.$GLOBALS['AppConfig']['system']['linksite'].'x.gif" class="att1" alt="القوات المهاجمة القادمة" title="هناك '.$war.' هجمات قادمة الى المعجزه هذه"> ';
echo '<b><font color="red">» '.$war.'</font></b>';
}else {
echo "-";
}
        echo "</td>";

        echo"</tr>\r\n\t\t";
    }
    }
    echo " </tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 4 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"world_player\" class=\"world\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"2\">";
    echo "إحصائيات";
    echo "</th></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "اللاعبين المسجلين";
    echo "</th>\r\n\t\t\t<td>";
    echo $this->generalData['players_count'];
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "اللاعبين النشيطين";
    echo "</th>\r\n\t\t\t<td>";
$q = new QueueModel();
        $qww = 172800;
$nn = $q->provider->fetchScalar( "SELECT COUNT(*) FROM p_players p WHERE TIME_TO_SEC(TIMEDIFF(NOW(), p.last_login_date)) <= %s", array( $qww) );

    echo $nn;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "اللاعبين المتصلين";
    echo "</th>\r\n\t\t\t<td>";
    echo $this->generalData['online_players_count'];
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "عدد القرى";
    echo "</th>\r\n\t\t\t<td>";
    echo $vnumber; 
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "عدد التحالفات";
    echo "</th>\r\n\t\t\t<td>";
    echo $adata;
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "عدد الابطال";
    echo "</th>\r\n\t\t\t<td>";
    echo $hnumber;
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "عدد حسابات البلاس الفعاله";
    echo "</th>\r\n\t\t\t<td>";
    echo $pnumber;
    echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"world_tribes\" class=\"world\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"3\">";
    echo LANGUI_STAT_T34;
    echo "</th></tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T49;
    echo "</td>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T35;
    echo "</td>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T36;
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo tribe_1;
    echo "</td>\r\n\t\t\t<td>";
    echo $this->generalData['Roman_players_count'];
    echo "</td>\r\n\t\t\t<td>";
    echo round( $this->generalData['Roman_players_count'] / $this->generalData['players_count'] * 100, 2 );
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo tribe_2;
    echo "</td>\r\n\t\t\t<td>";
    echo $this->generalData['Teutonic_players_count'];
    echo "</td>\r\n\t\t\t<td>";
    echo round( $this->generalData['Teutonic_players_count'] / $this->generalData['players_count'] * 100, 2 );
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo tribe_3;
    echo "</td>\r\n\t\t\t<td>";
    echo $this->generalData['Gallic_players_count'];
    echo "</td>\r\n\t\t\t<td>";
    echo round( $this->generalData['Gallic_players_count'] / $this->generalData['players_count'] * 100, 2 );
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo tribe_7;
    echo "</td>\r\n\t\t\t<td>";
    echo $this->generalData['Arab_players_count'];
    echo "</td>\r\n\t\t\t<td>";
    echo round( $this->generalData['Arab_players_count'] / $this->generalData['players_count'] * 100, 2 );
    echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";




while ( $this->miscellaneousList_1->next( ) )
    {
        $rpt_body_1 = explode('|', $this->miscellaneousList_1->row['rpt_body']);
        $s1 = $rpt_body_1[3];
        $s11 = explode(' ', $s1);
        $s111 = ($s11[0]+$s11[1]+$s11[2]+$s11[3]);
        $TroopKillAll_1 += $s111;
    }
        while ( $this->miscellaneousList_2->next( ) )
    {
        $rpt_body_2 = explode('|', $this->miscellaneousList_2->row['rpt_body']);
        $s2 = $rpt_body_2[3];
        $s22 = explode(' ', $s2);
        $s222 = ($s22[0]+$s22[1]+$s22[2]+$s22[3]);
        $TroopKillAll_2 += $s222;
        }
    
        while ( $this->miscellaneousList_3->next( ) )
    {
        $rpt_body_3 = explode('|', $this->miscellaneousList_3->row['rpt_body']);
        $s3 = $rpt_body_3[3];
        $s33 = explode(' ', $s3);
        $s333 = ($s33[0]+$s33[1]+$s33[2]+$s33[3]);
        $TroopKillAll_3 += $s333;
    }


        while ( $this->miscellaneousList_4->next( ) )
    {
        $rpt_body_4 = explode('|', $this->miscellaneousList_4->row['rpt_body']);
        $s4 = $rpt_body_4[3];
        $s44 = explode(' ', $s4);
        $s444 = ($s44[0]+$s44[1]+$s44[2]+$s44[3]);
        $TroopKillAll_4 += $s444;
    }


        while ( $this->miscellaneousList_5->next( ) )
    {
        $rpt_body_5 = explode('|', $this->miscellaneousList_5->row['rpt_body']);
        $s5 = $rpt_body_5[3];
        $s55 = explode(' ', $s5);
        $s555 = ($s55[0]+$s55[1]+$s55[2]+$s55[3]);
        $TroopKillAll_5 += $s555;
    }



        while ( $this->miscellaneousList_6->next( ) )
    {
        $rpt_body_6 = explode('|', $this->miscellaneousList_6->row['rpt_body']);
        $s6 = $rpt_body_6[3];
        $s66 = explode(' ', $s6);
        $s666 = ($s66[0]+$s66[1]+$s66[2]+$s66[3]);
        $TroopKillAll_6 += $s666;
    }



        while ( $this->miscellaneousList_7->next( ) )
    {
        $rpt_body_7 = explode('|', $this->miscellaneousList_7->row['rpt_body']);
        $s7 = $rpt_body_7[3];
        $s77 = explode(' ', $s7);
        $s777 = ($s77[0]+$s77[1]+$s77[2]+$s77[3]);
        $TroopKillAll_7 += $s777;
    }
#$TroopKillAll_1 = 0;
#$TroopKillAll_2 = 0;
#$TroopKillAll_3 = 0;
#$TroopKillAll_4 = 0;
#$TroopKillAll_5 = 0;
#$TroopKillAll_6 = 0;
#$TroopKillAll_7 = 0;

        echo '<table cellpadding="1" cellspacing="1" id="world_misc" class="world">';
    echo '<thead>';
    echo '<tr><th colspan="3">متنوعة</th></tr>';
    echo '<tr><td>الهجمات</td><td>السرقات</td><td>التاريخ</td></tr>';
    echo '</thead>';
    echo '<tbody>';
    echo '<tr><td>'. number_format($this->miscellaneousCount_1) .'</td><td>'. ( $TroopKillAll_1 == '' ? '0' : number_format($TroopKillAll_1) ) .'</td><td>'.date('d').'. '. $this->date_word(date('m')).'</td></tr>';
    echo '<tr><td>'. number_format($this->miscellaneousCount_2) .'</td><td>'. ( $TroopKillAll_2 == '' ? '0' : number_format($TroopKillAll_2) ) .'</td><td>'.date('d' ,strtotime('-1 days')) .'. '. $this->date_word(date('m')).'</td></tr>';
    echo '<tr><td>'. number_format($this->miscellaneousCount_3) .'</td><td>'. ( $TroopKillAll_3 == '' ? '0' : number_format($TroopKillAll_3) ) .'</td><td>'.date('d' ,strtotime('-2 days')) .'. '. $this->date_word(date('m')).'</td></tr>';
    echo '<tr><td>'. number_format($this->miscellaneousCount_4) .'</td><td>'. ( $TroopKillAll_4 == '' ? '0' : number_format($TroopKillAll_4) ) .'</td><td>'.date('d' ,strtotime('-3 days')) .'. '. $this->date_word(date('m')).'</td></tr>';
    echo '<tr><td>'. number_format($this->miscellaneousCount_5) .'</td><td>'. ( $TroopKillAll_5 == '' ? '0' : number_format($TroopKillAll_5) ) .'</td><td>'.date('d' ,strtotime('-4 days')) .'. '. $this->date_word(date('m')).'</td></tr>';
    echo '<tr><td>'. number_format($this->miscellaneousCount_6) .'</td><td>'. ( $TroopKillAll_6 == '' ? '0' : number_format($TroopKillAll_6) ) .'</td><td>'.date('d' ,strtotime('-5 days')) .'. '. $this->date_word(date('m')).'</td></tr>';
    echo '<tr><td>'. number_format($this->miscellaneousCount_7) .'</td><td>'. ( $TroopKillAll_7 == '' ? '0' : number_format($TroopKillAll_7) ) .'</td><td>'.date('d' ,strtotime('-6 days')) .'. '. $this->date_word(date('m')).'</td></tr>';

        
		
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"world_player\" class=\"world\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"2\">";
    echo "معلومات عامة";
    echo "</th></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "سرعة اللعبة";
    echo "</th>\r\n\t\t\t<td>";
	require(APP_PATH."config-f/s1.php");
    echo $AppConfig['Game']['speed'];
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "سرعة إرساليات الجيش";
    echo "</th>\r\n\t\t\t<td>";
    echo $AppConfig['Game']['attack'];
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "حمولة التجار";
    echo "</th>\r\n\t\t\t<td>";
    echo $AppConfig['Game']['market'];
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "سرعة تحرك التجار";
    echo "</th>\r\n\t\t\t<td>";
    echo $AppConfig['Game']['speedmarket'];
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "سعة المخازن";
    echo "</th>\r\n\t\t\t<td>";
    echo $AppConfig['Game']['capacity'];
	echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo "حماية المبتدئين";
    echo "</th>\r\n\t\t\t<td>";
    echo $AppConfig['Game']['protection'];
    echo "&nbsp;ساعة</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>";
    
    echo "</td></tr></tbody></table>";
      $result3 = mysqli_query($link, "SELECT * FROM p_queue WHERE proc_type = 13 or proc_type = 14");
    $numrows3=mysqli_num_rows($result3);
    
          $result32 = mysqli_query($link, "SELECT * FROM p_queue WHERE proc_type = 12");
    $numrows32=mysqli_num_rows($result32);
    
              $result31 = mysqli_query($link, "SELECT * FROM p_queue WHERE proc_type = 10");
    $numrows31=mysqli_num_rows($result31);
    $rand1 = rand(54,64);
    $rand2 = rand(23,100);
    $rand3 = rand(0,1);
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"world_player\" class=\"world\">\n";
    echo "	<thead>\n";
    echo "		<tr><th colspan=\"2\">تحركات سيرفر عودة التتار</th></tr>\n";
    echo "	</thead>\n";
    echo "	<tbody>\n";
    echo "		<tr>\n";
    echo "			<th>عدد الهجمات في سيرفر عودة التتار : <img src=\"core-f/style-f/default/img/a/att1.gif\">
    </th>\n";
    echo "			<td>".$numrows3."</td>\n";
    echo "		</tr>\n";
    echo "			<th>عدد التعزيزات في سيرفر عودة التتار : <img src=\"core-f/style-f/default/img/a/def2.gif\">
    </th>\n";
    echo "			<td>".$numrows32."</td>\n";
    echo "		</tr>\n";
    echo "			<th>عدد نقل الموارد : <img src=\"core-f/style-f/default/img/u/10.gif\">
    </th>\n";
    echo "			<td>".$numrows31."</td>\n";
    echo "		</tr>\n";
    echo "		</tr>\n";
    echo '</tbody></table>';
}
else if ( $this->selectedTabIndex == 13 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"player_off\" class=\"row_table_data\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
    echo LANGUI_STAT_T377;
    echo "\t\t\t<div id=\"submenu\">\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T10;
    echo "\" href=\"statistics?t=5\"><img class=\"btn_top10\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T10;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T11;
    echo "\" href=\"statistics";
    echo $this->selectedTabIndex == 6 ? "" : "?t=6";
    echo "\"><img class=\"";
    echo $this->selectedTabIndex == 6 ? "active btn_def" : "btn_def";
    echo "\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T11;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T12;
    echo "\" href=\"statistics";
    echo $this->selectedTabIndex == 7 ? "" : "?t=7";
    echo "\"><img class=\"";
    echo $this->selectedTabIndex == 7 ? "active btn_off" : "btn_off";
    echo "\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
	echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo "الناهب";
    echo "\" href=\"statistics";
    echo $this->selectedTabIndex == 13 ? "" : "?t=13";
    echo "\"><img class=\"";
    echo $this->selectedTabIndex == 13 ? "active btn_nhb" : "btn_nhb";
    echo "\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>\r\n\t\t\t</div></th></tr>\r\n\t\t<tr>\r\n\t\t\t<td></td><td>";
    echo LANGUI_STAT_T2;
    echo "</td><td>";
    echo LANGUI_STAT_T14;
    echo "</td><td>";
    echo LANGUI_STAT_T4;
    echo "</td><td>";
    echo LANGUI_STAT_T23;
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    while ( $this->dataList->next( ) )
    {
        ++$rowIndex;
        $rank = $rowIndex + $this->pageIndex * $this->pageSize;
        echo "\t\t<tr";
        if ( $this->selectedRank == $rank )
        {
            echo " class=\"hl\"";
        }
        echo ">\r\n\t\t   <td class=\"ra\">";
        echo $rank;
        echo ".</td>\r\n\t\t   <td class=\"pla\"><a href=\"profile?uid=";
        echo $this->dataList->row['id'];
        echo "\">";
        echo $this->dataList->row['name'];
        echo "</a> </td>\r\n\t\t   <td class=\"pop\">";
        echo number_format($this->dataList->row['total_people_count']);
        echo "</td>\r\n\t\t   <td class=\"vil\">";
        echo $this->dataList->row['villages_count'];
        echo "</td>\r\n\t\t   <td class=\"po\">";
        echo number_format($this->dataList->row['points']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo " </tbody>\r\n</table>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"search_navi\">\r\n\t<tbody>\r\n\t\t<tr>\t\t\t\t\t\t\r\n\t\t\t<td>\r\n\t\t\t<form method=\"post\" action=\"statistics";
    if ( 0 < $this->selectedTabIndex )
    {
        echo "?t=".$this->selectedTabIndex;
    }
    echo "\">\r\n\t\t\t\t<div class=\"search\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>:";
    echo LANGUI_STAT_T20;
    echo "<input type=\"text\" class=\"text ra\" maxlength=\"5\" name=\"rank\" value=\"";
    if ( 0 < $this->selectedRank )
    {
        echo $this->selectedRank;
    }
    echo "\"></span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan class=\"or\">";
    echo text_or_lang;
    echo "</span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>";
    echo LANGUI_STAT_T21;
    echo "<input type=\"text\" class=\"text name\" maxlength=\"20\" name=\"name\" value=\"\"></span>\r\n\t\t\t\t\t<input type=\"image\" value=\"submit\" name=\"submit\" id=\"btn_ok\" class=\"dynamic_img\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\">\r\n\t\t\t\t</div>\r\n\t\t\t</form>\r\n\t\t\t<div class=\"navi\">";
    echo $this->getPreviousLink( );
    echo "|";
    echo $this->getNextLink( );
    echo "</div>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";

}
else if ( $this->selectedTabIndex == 6 || $this->selectedTabIndex == 7 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"player_off\" class=\"row_table_data\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
    if ( $this->selectedTabIndex == 6 )
    {
        echo LANGUI_STAT_T37;
    }
    else
    {
        echo LANGUI_STAT_T38;
    }
    echo "\t\t\t<div id=\"submenu\">\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T10;
    echo "\" href=\"statistics?t=5\"><img class=\"btn_top10\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T10;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T11;
    echo "\" href=\"statistics";
    echo $this->selectedTabIndex == 6 ? "" : "?t=6";
    echo "\"><img class=\"";
    echo $this->selectedTabIndex == 6 ? "active btn_def" : "btn_def";
    echo "\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T11;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T12;
    echo "\" href=\"statistics";
    echo $this->selectedTabIndex == 7 ? "" : "?t=7";
    echo "\"><img class=\"";
    echo $this->selectedTabIndex == 7 ? "active btn_off" : "btn_off";
    echo "\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a><a title=\"";
    echo "الناهب";
    echo "\" href=\"statistics";
    echo $this->selectedTabIndex == 13 ? "" : "?t=13";
    echo "\"><img class=\"";
    echo $this->selectedTabIndex == 13 ? "active btn_nhb" : "btn_nhb";
    echo "\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>\r\n\t\t\t</div></th></tr>\r\n\t\t<tr>\r\n\t\t\t<td></td><td>";
    echo LANGUI_STAT_T2;
    echo "</td><td>";
    echo LANGUI_STAT_T14;
    echo "</td><td>";
    echo LANGUI_STAT_T4;
    echo "</td><td>";
    echo LANGUI_STAT_T23;
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    while ( $this->dataList->next( ) )
    {
        ++$rowIndex;
        $rank = $rowIndex + $this->pageIndex * $this->pageSize;
        echo "\t\t<tr";
        if ( $this->selectedRank == $rank )
        {
            echo " class=\"hl\"";
        }
        echo ">\r\n\t\t   <td class=\"ra\">";
        echo $rank;
        echo ".</td>\r\n\t\t   <td class=\"pla\"><a href=\"profile?uid=";
        echo $this->dataList->row['id'];
        echo "\">";
        echo $this->dataList->row['name'];
        echo "</a> </td>\r\n\t\t   <td class=\"pop\">";
        echo number_format($this->dataList->row['total_people_count']);
        echo "</td>\r\n\t\t   <td class=\"vil\">";
        echo $this->dataList->row['villages_count'];
        echo "</td>\r\n\t\t   <td class=\"po\">";
        echo number_format($this->dataList->row['points']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo " </tbody>\r\n</table>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"search_navi\">\r\n\t<tbody>\r\n\t\t<tr>\t\t\t\t\t\t\r\n\t\t\t<td>\r\n\t\t\t<form method=\"post\" action=\"statistics";
    if ( 0 < $this->selectedTabIndex )
    {
        echo "?t=".$this->selectedTabIndex;
    }
    echo "\">\r\n\t\t\t\t<div class=\"search\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>:";
    echo LANGUI_STAT_T20;
    echo "<input type=\"text\" class=\"text ra\" maxlength=\"5\" name=\"rank\" value=\"";
    if ( 0 < $this->selectedRank )
    {
        echo $this->selectedRank;
    }
    echo "\"></span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan class=\"or\">";
    echo text_or_lang;
    echo "</span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>";
    echo LANGUI_STAT_T21;
    echo "<input type=\"text\" class=\"text name\" maxlength=\"20\" name=\"name\" value=\"\"></span>\r\n\t\t\t\t\t<input type=\"image\" value=\"submit\" name=\"submit\" id=\"btn_ok\" class=\"dynamic_img\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\">\r\n\t\t\t\t</div>\r\n\t\t\t</form>\r\n\t\t\t<div class=\"navi\">";
    echo $this->getPreviousLink( );
    echo "|";
    echo $this->getNextLink( );
    echo "</div>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 9 || $this->selectedTabIndex == 10 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"alliance\" class=\"row_table_data\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"4\">";
    if ( $this->selectedTabIndex == 9 )
    {
        echo LANGUI_STAT_T39;
    }
    else
    {
        echo LANGUI_STAT_T40;
    }
    echo "\t\t\t<div id=\"submenu\">\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T10;
    echo "\" href=\"statistics?t=8\"><img class=\"btn_top10\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T10;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T11;
    echo "\" href=\"statistics?";
    echo $this->selectedTabIndex == 9 ? "t=1" : "t=9";
    echo "\"><img class=\"";
    if ( $this->selectedTabIndex == 9 )
    {
        echo "active ";
    }
    echo "btn_def\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T11;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T12;
    echo "\" href=\"statistics?";
    echo $this->selectedTabIndex == 10 ? "t=1" : "t=10";
    echo "\"><img class=\"";
    if ( $this->selectedTabIndex == 10 )
    {
        echo "active ";
    }
    echo "btn_off\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>\r\n\t\t\t</div>\r\n\t\t</th></tr>\r\n\t\t<tr>\r\n\t\t\t<td></td><td>";
    echo LANGUI_STAT_T13;
    echo "</td><td>";
    echo LANGUI_STAT_T2;
    echo "</td><td>";
    echo LANGUI_STAT_T23;
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $rowIndex = 0;
    while ( $this->dataList->next( ) )
    {
        ++$rowIndex;
        $rank = $rowIndex + $this->pageIndex * $this->pageSize;
        echo "\t\t<tr";
        if ( $this->selectedRank == $rank )
        {
            echo " class=\"hl\"";
        }
        echo ">\r\n\t\t   <td class=\"ra\">";
        echo $rank;
        echo ".</td>\r\n\t\t   <td class=\"al\"><a href=\"alliance?id=";
        echo $this->dataList->row['id'];
        echo "\">";
        echo $this->dataList->row['name'];
        echo "</a></td>\r\n\t\t   <td class=\"pla\">";
        echo $this->dataList->row['player_count'];
        echo "</td>\r\n\t\t   <td class=\"po\">";
        echo number_format($this->dataList->row['points']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo " </tbody>\r\n</table>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"search_navi\">\r\n\t<tbody>\r\n\t\t<tr>\t\t\t\t\t\t\r\n\t\t\t<td>\r\n\t\t\t<form method=\"post\" action=\"statistics";
    if ( 0 < $this->selectedTabIndex )
    {
        echo "?t=".$this->selectedTabIndex;
    }
    echo "\">\r\n\t\t\t\t<div class=\"search\">\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>:";
    echo LANGUI_STAT_T20;
    echo "<input type=\"text\" class=\"text ra\" maxlength=\"5\" name=\"rank\" value=\"";
    if ( 0 < $this->selectedRank )
    {
        echo $this->selectedRank;
    }
    echo "\"></span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan class=\"or\">";
    echo text_or_lang;
    echo "</span>\r\n\t\t\t\t\t";
    echo "<s";
    echo "pan>";
    echo LANGUI_STAT_T21;
    echo "<input type=\"text\" class=\"text name\" maxlength=\"20\" name=\"name\" value=\"\"></span>\r\n\t\t\t\t\t<input type=\"image\" value=\"submit\" name=\"submit\" id=\"btn_ok\" class=\"dynamic_img\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\">\r\n\t\t\t\t</div>\r\n\t\t\t</form>\r\n\t\t\t<div class=\"navi\">";
    echo $this->getPreviousLink( );
    echo "|";
    echo $this->getNextLink( );
    echo "</div>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 5 || $this->selectedTabIndex == 8 )
{
    echo "<table cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th>";
    if ( $this->selectedTabIndex == 5 )
    {
        echo LANGUI_STAT_T41;
    }
    else
    {
        echo LANGUI_STAT_T42;
    }
    echo "\t\t\t\r\n\t\t\t<div id=\"submenu\">\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T10;
    echo "\" href=\"statistics";
    echo $this->selectedTabIndex == 5 ? "" : "?t=1";
    echo "\"><img class=\"active btn_top10\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T10;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T11;
    echo "\" href=\"statistics?t=";
    echo $this->selectedTabIndex == 5 ? 6 : 9;
    echo "\"><img class=\"btn_def\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T11;
    echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo LANGUI_STAT_T12;
    echo "\" href=\"statistics?t=";
    echo $this->selectedTabIndex == 5 ? 7 : 10;
    echo "\"><img class=\"btn_off\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
	echo "\"></a>\r\n\t\t\t\t<a title=\"";
    echo "الناهب";
    echo "\" href=\"statistics?t=13";
    echo "\"><img class=\"btn_nhb\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T12;
    echo "\"></a>\r\n\t\t\t</div>\r\n\t\t\t";
    if ( $this->selectedTabIndex == 5 )
    {
    }
    echo "\t\t\t</th>\r\n\t\t</tr>\r\n\t</thead>\r\n</table><br>\r\n\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"top10_offs\" class=\"top10 row_table_data\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th><a href=\"#\" onclick=\"return showManual(6,";
    echo $this->selectedTabIndex == 5 ? 0 : 1;
    echo ");\"><img class=\"help\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T43;
    echo "\" title=\"";
    echo LANGUI_STAT_T43;
    echo "\"></a></th>\r\n\t\t\t<th colspan=\"3\">";
    echo LANGUI_STAT_T44;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T20;
    echo "</td>\r\n\t\t\t<td>";
    if ( $this->selectedTabIndex == 5 )
    {
        echo LANGUI_STAT_T2;
    }
    else
    {
        echo LANGUI_STAT_T13;
    }
    echo "</td>\r\n\t\t\t";
echo "\r\n\t\t<td>النقاط</td></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $_c = 0;
    while ( $this->top10Result['ATTACK']->next( ) )
    {
        ++$_c;
        echo "\t\t<tr";
        if ( $this->top10Result['TARGETID'] == $this->top10Result['ATTACK']->row['id'] )
        {
            echo " class=\"hl\"";
$s = $_c;
        }
        echo ">\r\n\t\t\t<td class=\"ra fc\">";
        echo $_c;
        echo ".&nbsp;</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
        echo $this->top10Result['URL'].$this->top10Result['ATTACK']->row['id'];
        echo "\">";
        if ( $this->top10Result['ATTACK']->row['color_name'] != '' )
        {
        if ($this->top10Result['ATTACK']->row['color_name'] == "#FFFFFF") {$this->top10Result['ATTACK']->row['color_name'] = "#000";}

        echo "<span style=\"color:".$this->top10Result['ATTACK']->row['color_name'].";\" >";
        }
        echo $this->top10Result['ATTACK']->row['name'];
        if ( $this->top10Result['ATTACK']->row['color_name'] != '' )
        {
        echo "</span>";
        }

        echo "</a></td>";
echo "\r\n\t\t\t<td class=\"val lc\">";
        echo number_format($this->top10Result['ATTACK']->row['points']);
        echo "</td>\r\n\t\t";
echo "</tr>\r\n\t\t";
    }
if ($s != '') {
$core = $s;
$m = "none";
}else {
$core = "?";
$m = "hl";
}
    echo "\t\t <tr>\r\n\t\t\t<td colspan=\"4\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t \t <tr class=\"own ".$m."\">\r\n\t\t\t<td class=\"ra fc\">".$core."</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
    echo $this->top10Result['URL'].$this->top10Result['TARGETID'];
    echo "\">";
    echo $this->top10Result['TARGETNAME'];
    echo "</a></td>\r\n\t\t\t";
echo "<td class=\"val lc\">";
    echo $this->top10Result['TARGEPOINT_ATTACK'];
    echo "</td>";
echo "\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"top10_defs\" class=\"top10 row_table_data\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th><a href=\"#\" onclick=\"return showManual(6,";
    echo $this->selectedTabIndex == 5 ? 0 : 1;
    echo ");\"><img class=\"help\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T43;
    echo "\" title=\"";
    echo LANGUI_STAT_T43;
    echo "\"></a></th>\r\n\t\t\t<th colspan=\"3\">";
    echo LANGUI_STAT_T45;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T20;
    echo "</td>\r\n\t\t\t<td>";
    if ( $this->selectedTabIndex == 5 )
    {
        echo LANGUI_STAT_T2;
    }
    else
    {
        echo LANGUI_STAT_T13;
    }
    echo "</td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td>";
  //  echo "التحالف";
    //echo "</td>";
}
echo "<td>".LANGUI_STAT_T23."</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $_c = 0;
    while ( $this->top10Result['DEFENSE']->next( ) )
    {
        ++$_c;
        echo "\t\t<tr";
        if ( $this->top10Result['TARGETID'] == $this->top10Result['DEFENSE']->row['id'] )
        {
            echo " class=\"hl\"";
        $s1 = $_c;
}
        echo ">\r\n\t\t\t<td class=\"ra fc\">";
        echo $_c;
        echo ".&nbsp;</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
        echo $this->top10Result['URL'].$this->top10Result['DEFENSE']->row['id'];
        echo "\">";
        if ( $this->top10Result['DEFENSE']->row['color_name'] != '' )
        {
        if ($this->top10Result['DEFENSE']->row['color_name'] == "#FFFFFF") {$this->top10Result['DEFENSE']->row['color_name'] = "#000";}
        echo "<span style=\"color:".$this->top10Result['DEFENSE']->row['color_name'].";\" >";
        }
        echo $this->top10Result['DEFENSE']->row['name'];
        if ( $this->top10Result['DEFENSE']->row['color_name'] != '' )
        {
        echo "</span>";
        }        echo "</a></td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td class=\"val lc\"><a href='alliance?id=".$this->top10Result['DEFENSE']->row['alliance_id']."'>";
        //echo $this->top10Result['DEFENSE']->row['alliance_name'];
       // echo "</a></td>";
}

echo "<td class=\"val lc\">";
        echo number_format($this->top10Result['DEFENSE']->row['points']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
if ($s1 != '') {
$core = $s1;
$m = "none";
}else {
$core = "?";
$m = "hl";
}
    echo "\t\t <tr>\r\n\t\t\t<td colspan=\"4\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t \t <tr class=\"own ".$m."\">\r\n\t\t\t<td class=\"ra fc\">".$core."</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
    echo $this->top10Result['URL'].$this->top10Result['TARGETID'];
    echo "\">";
    echo $this->top10Result['TARGETNAME'];
    echo "</a></td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td class=\"val lc\"><a href='alliance?id=".$this->data['alliance_id']."'>";
  //      echo $this->data['alliance_name'];
     //   echo "</a></td>";
}
echo "<td class=\"val lc\">";
    echo $this->top10Result['TARGEPOINT_DEFENSE'];
    echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n<div class=\"clear\"></div>\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"top10_climbers\" class=\"top10 row_table_data\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th><a href=\"#\" onclick=\"return showManual(6,";
    echo $this->selectedTabIndex == 5 ? 0 : 1;
    echo ");\"><img class=\"help\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T43;
    echo "\" title=\"";
    echo LANGUI_STAT_T43;
    echo "\"></a></th>\r\n\t\t\t<th colspan=\"3\">";
    echo LANGUI_STAT_T46;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T20;
    echo "</td>\r\n\t\t\t<td>";
    if ( $this->selectedTabIndex == 5 )
    {
        echo LANGUI_STAT_T2;
    }
    else
    {
        echo LANGUI_STAT_T13;
    }
    echo "</td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td>";
  //  echo "التحالف";
    //echo "</td>";
}
echo "<td>".LANGUI_STAT_T50."</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $_c = 0;
    while ( $this->top10Result['DEV']->next( ) )
    {
        ++$_c;
        echo "\t\t<tr";
        if ( $this->top10Result['TARGETID'] == $this->top10Result['DEV']->row['id'] )
        {
            echo " class=\"hl\"";
        $s2 = $_c;
}
        echo ">\r\n\t\t\t<td class=\"ra fc\">";
        echo $_c;
        echo ".&nbsp;</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
        echo $this->top10Result['URL'].$this->top10Result['DEV']->row['id'];
        echo "\">";
        if ( $this->top10Result['DEV']->row['color_name'] != '' )
        {
        if ($this->top10Result['DEV']->row['color_name'] == "#FFFFFF") {$this->top10Result['DEV']->row['color_name'] = "#000";}

        echo "<span style=\"color:".$this->top10Result['DEV']->row['color_name'].";\" >";
        }
        echo $this->top10Result['DEV']->row['name'];
        if ( $this->top10Result['DEV']->row['color_name'] != '' )
        {
        echo "</span>";
        }
        echo "</a></td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td class=\"val lc\"><a href='alliance?id=".$this->top10Result['DEV']->row['alliance_id']."'>";
        //echo $this->top10Result['DEV']->row['alliance_name'];
       // echo "</a></td>";
}
echo "<td class=\"val lc\">";
        echo number_format($this->top10Result['DEV']->row['points']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
if ($s2 != '') {
$core = $s2;
$m = "none";
}else {
$core = "?";
$m = "hl";
}
    echo "\t\t <tr>\r\n\t\t\t<td colspan=\"4\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t \t <tr class=\"own ".$m."\">\r\n\t\t\t<td class=\"ra fc\">".$core."</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
    echo $this->top10Result['URL'].$this->top10Result['TARGETID'];
    echo "\">";
    echo $this->top10Result['TARGETNAME'];
    echo "</a></td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td class=\"val lc\"><a href='alliance?id=".$this->data['alliance_id']."'>";
  //      echo $this->data['alliance_name'];
    //    echo "</a></td>";
}
echo "<td class=\"val lc\">";
    echo $this->top10Result['TARGEPOINT_DEV'];
    echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"top10_raiders\" class=\"top10 row_table_data\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th><a href=\"#\" onclick=\"return showManual(6,";
    echo $this->selectedTabIndex == 5 ? 0 : 1;
    echo ");\"><img class=\"help\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" alt=\"";
    echo LANGUI_STAT_T43;
    echo "\" title=\"";
    echo LANGUI_STAT_T43;
    echo "\"></a></th>\r\n\t\t\t<th colspan=\"3\">";
    echo LANGUI_STAT_T47;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo LANGUI_STAT_T20;
    echo "</td>\r\n\t\t\t<td>";
    if ( $this->selectedTabIndex == 5 )
    {
        echo LANGUI_STAT_T2;
    }
    else
    {
        echo LANGUI_STAT_T13;
    }
    echo "</td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td>";
  //  echo "التحالف";
    //echo "</td>";
}
echo "<td>".LANGUI_STAT_T48."</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    $_c = 0;
    while ( $this->top10Result['THIEF']->next( ) )
    {
        ++$_c;
        echo "\t\t<tr";
        if ( $this->top10Result['TARGETID'] == $this->top10Result['THIEF']->row['id'] )
        {
            echo " class=\"hl\"";
       $s3 = $_c;
 }
        echo ">\r\n\t\t\t<td class=\"ra fc\">";
        echo $_c;
        echo ".&nbsp;</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
        echo $this->top10Result['URL'].$this->top10Result['THIEF']->row['id'];
        echo "\">";
        if ( $this->top10Result['THIEF']->row['color_name'] != '' )
        {
        if ($this->top10Result['THIEF']->row['color_name'] == "#FFFFFF") {$this->top10Result['THIEF']->row['color_name'] = "#000";}

        echo "<span style=\"color:".$this->top10Result['THIEF']->row['color_name'].";\" >";
        }
        echo $this->top10Result['THIEF']->row['name'];
        if ( $this->top10Result['THIEF']->row['color_name'] != '' )
        {
        echo "</span>";
        }                echo "</a></td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td class=\"val lc\"><a href='alliance?id=".$this->top10Result['THIEF']->row['alliance_id']."'>";
    //    echo $this->top10Result['THIEF']->row['alliance_name'];
  //      echo "</a></td>";
}

echo "<td class=\"val lc\">";
        echo number_format($this->top10Result['THIEF']->row['points']);
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
if ($s3 != '') {
$core = $s3;
$m = "none";
}else {
$core = "?";
$m = "hl";
}
    echo "\t\t <tr>\r\n\t\t\t<td colspan=\"4\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t \t <tr class=\"own ".$m."\">\r\n\t\t\t<td class=\"ra fc\">".$core."</td>\r\n\t\t\t<td class=\"pla\"><a href=\"";
    echo $this->top10Result['URL'].$this->top10Result['TARGETID'];
    echo "\">";
    echo $this->top10Result['TARGETNAME'];
    echo "</a></td>\r\n\t\t\t";
if ($this->selectedTabIndex == 5) {
//echo "<td class=\"val lc\"><a href='alliance?id=".$this->data['alliance_id']."'>";
//        echo $this->data['alliance_name'];
//        echo "</a></td>";
}
echo "<td class=\"val lc\">";
    echo $this->top10Result['TARGEPOINT_THIEF'];
    echo "</td>";
echo "\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
}
if ($this->selectedTabIndex == 12) {
echo "<h1>ملوك عودة التتار</h1>ملوك عودة التتار هم من يحققون ارقام قياسيه ولايستطيع اي لاعب بل اي تحالف تحقيقه يتم رفع اسمائهم هنا لكي يأتي غيرهم ويكسر ارقامهم القياسيه يتم التصفيه كل نهايه عودة التتار";

$f1 = ROOT_PATH.DIRECTORY_SEPARATOR."core-f/stx/kings/att.txt";
$f2 = ROOT_PATH.DIRECTORY_SEPARATOR."core-f/stx/kings/deff.txt";
$f3 = ROOT_PATH.DIRECTORY_SEPARATOR."core-f/stx/kings/dev.txt";
$f4 = ROOT_PATH.DIRECTORY_SEPARATOR."core-f/stx/kings/win.txt";
$f5 = ROOT_PATH.DIRECTORY_SEPARATOR."core-f/stx/kings/hero.txt";
$att[1] = 0;
$deff[1] = 0;
$win[1] = 0;
$dev[1] = 0;
$hero[1] = 0;
if(file_exists($f1)){
$fpa = fopen($f1, 'r');
$r1 = fread($fpa, filesize($f1));
$att = explode ("|", $r1);
}
if(file_exists($f2)){
$fpd = fopen($f2, 'r');
$r2 = fread($fpd, filesize($f2));
$deff = explode ("|", $r2);
}
if(file_exists($f3)){
$fpv = fopen($f3, 'r');
$r3 = fread($fpv, filesize($f3));
$dev = explode ("|", $r3);
}
if(file_exists($f4)){
$fpw = fopen($f4, 'r');
$r4 = fread($fpw, filesize($f4));
$win = explode ("|", $r4);
}
if(file_exists($f5)){
$fph = fopen($f5, 'r');
$r5 = fread($fph, filesize($f5));
$hero = explode ("|", $r5);
}
$ratt  = $this->queueModel->provider->fetchRow("SELECT id FROM p_players WHERE email='".$att[2]."'");
$rdeff = $this->queueModel->provider->fetchRow("SELECT id FROM p_players WHERE email='".$deff[2]."'");
$rdev  = $this->queueModel->provider->fetchRow("SELECT id FROM p_players WHERE email='".$dev[2]."'");
$rwin  = $this->queueModel->provider->fetchRow("SELECT id FROM p_players WHERE email='".$win[2]."'");
$rhero = $this->queueModel->provider->fetchRow("SELECT id FROM p_players WHERE email='".$hero[2]."'");
?>
<table cellpadding="1" cellspacing="1" id="world_tribes" class="world">
        <thead>
                <tr><th colspan="3">ملوك عودة التتار</th></tr>
                <tr>
                        <td>اسم الاعب</td>
                        <td>التصنيف</td>
                        <td>النقاط المحققه</td>
                </tr>
        </thead>
        <tbody>
                <tr>
                        <td><?php if ($ratt['id'] > 0) {echo "<a href='profile.php?uid=".$ratt['id']."'>";} ?><b><?php echo $att[0]; ?></b></a></td>
                        <td>حقق رقم قياسي في الهجوم</td>
                        <td><?php echo number_format($att[1]); ?></td>
                </tr>
                <tr>
                        <td><?php if ($rdeff['id'] > 0) {echo "<a href='profile.php?uid=".$rdeff['id']."'>";} ?><b><?php echo $deff[0]; ?></b></a></td>
                        <td>حقق رقم قياسي في الدفاع</td>
                        <td><?php echo number_format($deff[1]); ?></td>
                </tr>
                <tr>
                        <td><?php if ($rwin['id'] > 0) {echo "<a href='profile.php?uid=".$rwin['id']."'>";} ?><b><?php echo $win[0]; ?></b></a></td>
                        <td>حقق رقم قياسي في النهب</td>
                        <td><?php echo number_format($win[1]); ?></td>
                </tr>
                <tr>
                        <td><?php if ($rdev['id'] > 0) {echo "<a href='profile.php?uid=".$rdev['id']."'>";} ?><b><?php echo $dev[0]; ?></b></a></td>
                        <td>حقق أكبر امبراطوريه</td>
                        <td><?php echo number_format($dev[1]); ?></td>
                </tr>
                <tr>
                        <td><?php if ($rhero['id'] > 0) {echo "<a href='profile.php?uid=".$rhero['id']."'>";} ?><b><?php echo $hero[0]; ?></b></a></td>
                        <td>درب اقوى بطل (<?php echo $hero[3]; ?>)</td>
                        <td><?php echo number_format($hero[1]); ?></td>
                </tr>
        </tbody>
</table>

<p>

<table cellpadding="1" cellspacing="1">
        <thead>
                <tr><th colspan="6">ملوك الجولات السابقه</th></tr>
                <tr>
                        <td>الجوله</td>
                        <td>اسم الملك</td>
                        <td>التحالف</td>
                        <td>القبيلة</td>
                        <td>الدولة</td>
                        <td>تاريخ الفوز</td>
                </tr>
        </thead>
        <tbody>
<!--<tr><th colspan="6"><font color="red">كن انت اول الملوك في عودة التتار عودة التتار</font></th></tr>-->
<td><b>1</b></td>
<td><b><!--<a href="profile?uid=5">-->فزعة</a></b></td>
<td><b>فــــزعة</b></td>
<td><b><img src="core-f/stx/flags/19.gif" alt="الجرمان" title="الجرمان"></b></td>
<td><b><img src="core-f/stx/flags/sa.webp" alt="السعودية" title="السعودية"></b></td>
<td>2015-10-03</td>
</tr><tr>

<td><b>2</b></td>
<td><b><a href="profile?uid=87">samer</a></b></td>
<td><b>خآآص</b></td>
<td><b><img src="core-f/stx/flags/19.gif" alt="الجرمان" title="الجرمان"></b></td>
<td><b><img src="core-f/stx/flags/sa.webp" alt="السعودية" title="السعودية"></b></td>
<td>2015-10-09</td>

<!--</tr><tr>
<td><b>-</b></td>
<td><b><a href="profile?uid=37">-</a></b></td>
<td><b>-</b></td>
<td><b><img class="unit u9" src="core-f/style-f/x.gif" alt="الرومان" title="الرومان"></b></td>
<td><b><img src="core-f/stx/flags/unknown.webp" alt="?" title="?"></b></td>
<td>-</td>-->
</tr></tbody>
</table>
<p>
كن انت ملك هذا الجوله ليتم نحت اسمك فوق
<?php
}
?>
</body>
</html>