<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<div id="textmenu">
<a href="travianar?t=3" <?php if ($_GET['t'] == 4) {?>class="selected"<?php } ?> ><center>تمكنك هذه الخاصية من اضافة الواحات القريبة بشكل تلقائي في قائمة المزارع</center></a>
</div>
<?php 
if($this->selectedTabIndex == 4){ 
?>
<form method="POST" action="travianar.php?t=2&allv">
<h4>اضافه قراك الى قائمه المزارع </h4>
<div class="option" style="padding: 12px;">
<?php 
$t_arr = explode( '|', $this->data['troops_num'] );
                        foreach( $t_arr as $t_str ) {
                                $t2_arr = explode( ':', $t_str );
                                if ( $t2_arr[0] == -1 ) {
                                        $t2_arr = explode( ',', $t2_arr[1] );
                                        foreach( $t2_arr as $t2_str ) {
                                                $t = explode( ' ', $t2_str );
                                                if ( $t[0] == 4 || $t[0] == 7 || $t[0] == 8 || $t[0] == 9 || $t[0] == 10 
                                                  || $t[0] == 14 || $t[0] == 17 || $t[0] == 18 || $t[0] == 19 || $t[0] == 20 
                                                  || $t[0] == 23 || $t[0] == 27 || $t[0] == 28 || $t[0] == 29 || $t[0] == 30 || $t[0] == 99
                                                  || $t[0] == 54 || $t[0] == 57 || $t[0] == 58 || $t[0] == 59 || $t[0] == 60 ){
                                                        continue;
                                                }
                                                        $troops [ $t[0] ] = $t[1];
                                        }
                                }
                        }
switch($this->data['tribe_id']){
        case 1:
                $farmTroops = array(1,2,3,5,6);
                break;
        case 2:
                $farmTroops = array(11,12,13,15,16);
                break;
        case 3:
                $farmTroops = array(21,22,24,25,26);
                break;
        case 6:
                $farmTroops = array(51,52,53,55,56);
                break;
      case 7:
                $farmTroops = array(100,101,102,104,105);
                break;
}
foreach($farmTroops as $tid){
foreach($troops as $troopId=>$troopNum){
        if($tid == $troopId){$num = $troopNum;}
}
?><label><input type="text" value="0" name="t[<?php echo $tid; ?>]" class="text" style="width:10%"> <img class="unit u<?php echo $tid; ?>" src="core-f/style-f/x.gif" alt="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>" title="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>"> <b><?php echo $num; ?></b> <?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?></label><br><?php } ?>
</div>
<div style="float:right;margin-top:10px;">
<button type="submit" value="اضافة مزرعة" name="s1" id="btn_ok"><div class="button-container"><div class="button-position"><div class="btl"><div class="btr"><div class="btc"></div></div></div><div class="bml"><div class="bmr"><div class="bmc"></div></div></div><div class="bbl"><div class="bbr"><div class="bbc"></div></div></div></div><div class="button-contents">اضافة مزرعة</div></div></button>
</div>
<?php
}
if($this->selectedTabIndex == 3){ 
?>
<script src="core-f/style-f/js/jquery.js" type="text/javascript"></script>
<script>var texting = "يرجى الانتظار يتم اضافة الواحات الان";</script>
<script type="text/javascript" src="core-f/style-f/js/secretaddfarmjs4.js?cach_fukc_a" ></script>
<div id="farming"></div><br>
<?php
$result = $this->find1();
$more = $this->find2();
$currentLooting = $this->find3();
$q                      = new QueueModel();
$num_farm = $q->provider->fetchScalar('SELECT num_farm FROM p_players WHERE id="'.$this->player->playerId.'" ');

$count = ($num_farm+100);
echo "<center>".LANGUI_FARMFINDER_T6.$count."</center>";
echo "<br>";
echo "<br>";
?>
<form action='' name='farm' method="post">
<table id="plusFunctions" cellpadding="1" cellspacing="1">
<thead>
<tr>
<th colspan="5"><?php echo LANGUI_FARMFINDER_T3; ?></th>
</tr>
<tr>
<td style="width: 10%"><input type='checkbox' onclick='CheckAll(this.checked)'></td>
<td style="width: 12%">x</td>
<td style="width: 12%">y</td>
<td style="width: 40%"><?php echo LANGUI_FARMFINDER_T1; ?></td>
<td style="width: 26%"><?php echo LANGUI_FARMFINDER_T2; ?></td>
</tr>
</thead>
<tbody>
<?php

  while($result->next( ))
  {
  $row = $result->row;
  $distance = WebHelper::getDistance($this->data['rel_x'], $this->data['rel_y'], $row['rel_x'], $row['rel_y'], $this->setupMetadata['map_size']/2);
  if(isset($rows[round($distance)]))
  {
  $rows[round($distance)] = $rows[round($distance)]."|-|".$result->row['rel_x']."|".$result->row['rel_y']."|".$result->row['player_name']."|".$result->row['id'];
  } else {
  $rows[round($distance)] = $result->row['rel_x']."|".$result->row['rel_y']."|".$result->row['player_name']."|".$result->row['id'];
  }
  }
  ksort($rows);
          $ii = 0;
  foreach($rows as $distance => $row)
  {
     
$array1 = explode("|-|", $row);
foreach($array1 as $key => $value)
{
$array2 = explode("|", $value);
if(!in_array($array2[3], $currentLooting)){
    $ii += 1;

    echo "<tr><td id='a".$ii."'><center><input class='check' type='checkbox' name='list[]' id='list' value='".$array2[0]."|".$array2[1]."|".$array2[3]."'></center></td><td id='b".$ii."'><center>".$array2[0]."</center></td><td id='c".$ii."'><center>".$array2[1]."</center></td><td id='d".$ii."'><center>".(($array2[2] == "") ? "-" : $array2[2])."</center></td><td id='e".$ii."'><center>".$distance."</center></td></tr>";
}
}
if($ii >= $count)
{
break;
}
}
?>
</tbody>
</table>
<h3>القوات<h3/>
<div class="option" style="padding: 12px;">
<?php 
$t_arr = explode( '|', $this->data['troops_num'] );
                        foreach( $t_arr as $t_str ) {
                                $t2_arr = explode( ':', $t_str );
                                if ( $t2_arr[0] == -1 ) {
                                        $t2_arr = explode( ',', $t2_arr[1] );
                                        foreach( $t2_arr as $t2_str ) {
                                                $t = explode( ' ', $t2_str );
                                                if ( $t[0] == 4 || $t[0] == 7 || $t[0] == 8 || $t[0] == 9 || $t[0] == 10 
                                                  || $t[0] == 14 || $t[0] == 17 || $t[0] == 18 || $t[0] == 19 || $t[0] == 20 
                                                  || $t[0] == 23 || $t[0] == 27 || $t[0] == 28 || $t[0] == 29 || $t[0] == 30 || $t[0] == 99
                                                  || $t[0] == 54 || $t[0] == 57 || $t[0] == 58 || $t[0] == 59 || $t[0] == 60 ){
                                                        continue;
                                                }
                                                        $troops [ $t[0] ] = $t[1];
                                        }
                                }
                        }
switch($this->data['tribe_id']){
        case 1:
                $farmTroops = array(1,2,3,5,6);
                break;
        case 2:
                $farmTroops = array(11,12,13,15,16);
                break;
        case 3:
                $farmTroops = array(21,22,24,25,26);
                break;
        case 6:
                $farmTroops = array(51,52,53,55,56);
                break;
      case 7:
                $farmTroops = array(100,101,102,104,105);
                break;
}
foreach($farmTroops as $tid){
foreach($troops as $troopId=>$troopNum){
        if($tid == $troopId){$num = $troopNum;}
}
?><label><input type="text" value="0" name="t[<?php echo $tid; ?>]" data-troops="<?php echo $tid; ?>" class="text troops-text" style="width:10%"> <img class="unit u<?php echo $tid; ?>" src="core-f/style-f/x.gif" alt="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>" title="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>"> <b><?php echo $num; ?></b> <?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?></label><br><?php } ?>
</div>
<input class="text" name="attack" type="button" value="اضافه" onClick="javascript:farming();scrollTo(0,0);">

</form>
<br>
<br>

<?php
}else
if($this->selectedTabIndex == 0){ 
?>
<script src="core-f/style-f/js/jquery.js" type="text/javascript"></script>
<script>var texting = "جاري الهجوم";</script>
<script type="text/javascript" src="core-f/style-f/js/secretfarmjs.js"></script>
<div id="farming"></div><br>
<form name='farm'>
<table id="plusFunctions" cellpadding="1" cellspacing="1"><thead>
<th colspan="5">قائمة المزارع</th>
<tr>
<td style="width: 3%"><input type='checkbox' onclick='CheckAll(this.checked)'></td>
     <td style="width: 45%">الاسم</td>
     <td style="width: 4%">السكان</td>
     <td style="width: 45%">الجيش</td>
     <td style="width: 3%"><a href="travianar.php?delall"><img src="<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>x.gif" class="del" title="حذف جميع المزارع"></a></td>
</tr>
</thead><tbody>

<?php
$start = 0;
if($this->data['tribe_id'] == 2)
{
$start = 10;
}
if($this->data['tribe_id'] == 3)
{
$start = 20;
}
if($this->data['tribe_id'] == 6)
{
$start = 50;
}
if($this->data['tribe_id'] == 7)
{
$start = 99;
}
if($this->data['tribe_id'] == 8)
{
$start = 60;
}
if($this->data['tribe_id'] == 9)
{
$start = 70;
}

$q2 = new QueueModel();
$ii = 0;
while ($this->get_looting->next ())
{
$ii += 1;
$t = true;
$vid= $q2->provider->fetchRow("SELECT village_name,people_count FROM p_villages WHERE id='".$this->get_looting->row['avid']."'");
$troop = explode('=', $this->get_looting->row['troops']);
if ($vid['village_name'] == '') {
$vname = 'واحة';
$pp = "-";
}else {
$vname = $vid['village_name'];
$pp = $vid['people_count'];
}
?>
<tr>
<?php
echo "<td id='a".$ii."'><center><input class='check' type='checkbox' name='list[]' id='list' value='".$this->get_looting->row['avid']."|".$this->get_looting->row['x']."|".$this->get_looting->row['y']."|".($start+$troop[0])."|".$this->get_looting->row['troops']."'></center></td>";
?>
     <td id='b<?php echo $ii; ?>'><a href='village3?id=<?php echo $this->get_looting->row['avid']; ?>'> (<?php echo $this->get_looting->row['x']; ?>|<?php echo $this->get_looting->row['y']; ?>) <?php echo $vname; ?></a></td>
     <td id='c<?php echo $ii; ?>'><center><?php echo $pp; ?></center></td>
     <td id='d<?php echo $ii; ?>'><center>
<?php 
$test = $this->get_looting->row['troops'];
$t2_arr = explode (',', $test);
foreach ($t2_arr as $t2_str)
{
$t = explode (' ', $t2_str);
if ($t[1] <= 0) {
continue;
}
?><img class='unit u<?php echo $t[0]; ?>' src='<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>x.gif'> <?php echo $t[1];
}

?>
</center></td>
     <td id='e<?php echo $ii; ?>'><center><a href='travianar.php?del=<?php echo $this->get_looting->row['id']; ?>'><img class='del' src='<?php echo $GLOBALS['AppConfig']['system']['linksite']; ?>x.gif'></a></center></td>
</tr>
<?php
}
if(!$t)
{
     echo '<tr><td colspan="5"><center>'.LANGUI_FARM_T4.'</center></td></tr>';
}
?>
</tbody>
</table><p>
<input class="text" name="attack" type="button" value="هجوم" onClick="javascript:farming();scrollTo(0,0);">
</form>

<?php } elseif($this->selectedTabIndex == 1){ ?>
<span class="error"><?php echo $this->error; ?></span>
<form action="travianar.php?t=1" method="POST">
<table cellspacing="1" cellpadding="1" id="brought_in">
<thead>
     <tr><th colspan="4"><center>الاعدادات العامة</center></th></tr>
</thead>
<tr>
     <td><center>ارسال الهجومات</center></td>
     <td><center>كل <select name="time">
<option <?php echo ($this->looting_send_every['looting_send_every'] == 4 ? 'selected' : ''); ?> value="4">ايقاف</option>
<option <?php echo ($this->looting_send_every['looting_send_every'] == 30 ? 'selected' : ''); ?> value="30">30</option>
<option <?php echo ($this->looting_send_every['looting_send_every'] == 45 ? 'selected' : ''); ?> value="45">45</option>
<option <?php echo ($this->looting_send_every['looting_send_every'] == 60 ? 'selected' : ''); ?> value="60">60</option>
<option <?php echo ($this->looting_send_every['looting_send_every'] == 90 ? 'selected' : ''); ?> value="90">90</option>
<option <?php echo ($this->looting_send_every['looting_send_every'] == 120 ? 'selected' : ''); ?> value="120">120</option>
     </select> دقيقه</center></td>
     <td colspan="2"><input class="text" name="add" type="submit" value="حفظ"> </td>
</tr>
</table>
<br>
</form>
<?php } elseif($this->selectedTabIndex == 2){
$start = 0;
if($this->data['tribe_id'] == 2)
{
$start = 10;
}
if($this->data['tribe_id'] == 3)
{
$start = 20;
}
if($this->data['tribe_id'] == 6)
{
$start = 50;
}
if($this->data['tribe_id'] == 7)
{
$start = 99;
}
if($this->data['tribe_id'] == 8)
{
$start = 60;
}
if($this->data['tribe_id'] == 9)
{
$start = 70;
}
?>
<span class="error"><?php echo $this->error; ?></span>
<form method="POST" action="travianar.php?t=2">
<h4>اضافة مزرعة جديدة</h4>
<table cellspacing="1" cellpadding="1" id="coords">
<tbody><tr>
<td>
<div class="option" style="padding: 12px;">
<?php 
$t_arr = explode( '|', $this->data['troops_num'] );
                        foreach( $t_arr as $t_str ) {
                                $t2_arr = explode( ':', $t_str );
                                if ( $t2_arr[0] == -1 ) {
                                        $t2_arr = explode( ',', $t2_arr[1] );
                                        foreach( $t2_arr as $t2_str ) {
                                                $t = explode( ' ', $t2_str );
                                                if ( $t[0] == 4 || $t[0] == 7 || $t[0] == 8 || $t[0] == 9 || $t[0] == 10 
                                                  || $t[0] == 14 || $t[0] == 17 || $t[0] == 18 || $t[0] == 19 || $t[0] == 20 
                                                  || $t[0] == 23 || $t[0] == 27 || $t[0] == 28 || $t[0] == 29 || $t[0] == 30 || $t[0] == 99
                                                  || $t[0] == 54 || $t[0] == 57 || $t[0] == 58 || $t[0] == 59 || $t[0] == 60 ){
                                                        continue;
                                                }
                                                        $troops [ $t[0] ] = $t[1];
                                        }
                                }
                        }
switch($this->data['tribe_id']){
        case 1:
                $farmTroops = array(1,2,3,5,6);
                break;
        case 2:
                $farmTroops = array(11,12,13,15,16);
                break;
        case 3:
                $farmTroops = array(21,22,24,25,26);
                break;
        case 6:
                $farmTroops = array(51,52,53,55,56);
                break;
      case 7:
                $farmTroops = array(100,101,102,104,105);
                break;
}
foreach($farmTroops as $tid){
foreach($troops as $troopId=>$troopNum){
        if($tid == $troopId){$num = $troopNum;}
}
?><label><input type="text" value="0" name="t[<?php echo $tid; ?>]" class="text" style="width:10%"> <img class="unit u<?php echo $tid; ?>" src="core-f/style-f/x.gif" alt="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>" title="<?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?>"> <b><?php echo $num; ?></b> <?php echo htmlspecialchars( constant( "troop_".($tid) ) ); ?></label><br><?php } ?>
</div>
</td>


<td>
<table cellspacing="1" cellpadding="1" id="coords">
	<tbody>
		<tr>
			<td></td>
		</tr>
		<tr>
			<td class="target"><span>X:</span><input type="text" maxlength="4" value="<?php echo $this->x; ?>" name="x" class="text"> <span>Y:</span><input type="text" maxlength="4" value="<?php echo $this->y; ?>" name="y" class="text"></td>
		</tr>
	</tbody>
</table>

</td>
</tr>
</tbody></table>
<div class="clear"></div>
<div style="float:right;margin-top:10px;">
<button type="submit" value="اضافة مزرعة" name="s1" id="btn_ok"><div class="button-container"><div class="button-position"><div class="btl"><div class="btr"><div class="btc"></div></div></div><div class="bml"><div class="bmr"><div class="bmc"></div></div></div><div class="bbl"><div class="bbr"><div class="bbc"></div></div></div></div><div class="button-contents">اضافة مزرعة</div></div></button>
</div>
<div class="clear"></div>
<br>
<div class="clear"></div>
<br>
<br>
</form>
</body>
</html>
<?php } elseif($this->selectedTabIndex == 3){ ?>
يجب عليك تفعيل خاصيه النهب المتطور من قائمة بلاس
<?php } ?>